### ISSUE TITLE
Updated to new 2.0 vesion, and, well... all is white!

### ISSUE THREAD

**Issue by yepMad** [Dustyroom/flat-kit-doc#1]
I upgraded from 1.9 to 2.0 and apparently all materials had the "Color" parameter reset to white. Was there a warning for this somewhere? Is there a way to revert?

**Comment by dustyroom-studio** [comment]
Sorry for making a breaking change without a warning.

We have changed the name from `_Color` to `_BaseColor` and from `_MainTex` to `_BaseMap` to be able to support new versions of URP.

However, there is a workaround:
1. Go to the file `Assets/FlatKit/Shaders/Editor/StylizedSurfaceEditor.cs` and uncomment these lines (or simply add a `/` symbol on the first line):
    ```
        /*
        if (HasProperty("_MainTex")) {
            TransferToBaseMap();
        }
        //*/
    ```
1. In your project, seleact each material that uses a Flat Kit shader.
1. Restore the file from step 1 to its original state.

**Comment by yepMad** [comment]
Thank you! In this case, I have already manually updated the colors. Do I need to do anything?

**Comment by dustyroom-studio** [comment]
Then you're all done. Closing the issue.
