### ISSUE TITLE
Cant get URP version to download from asset store or package manger

### ISSUE THREAD

**Issue by tgamorris76** [Dustyroom/flat-kit-doc#10]
Have tried both package manager and asset store and they both default to built in. Didnt have any problems before but since the latest update have been unable to.

**Comment by dustyroom-studio** [comment]
There's an issue going on with Unity Package Manager, which Unity is aware of. It doesn't allow to download the latest versions of the assets. Lots of developers including us are requesting Unity to fix it. meanwhile you can try a few things.

If you are using an older version of Unity, please update it to a more recent one, 2020.2.

Prior to re-importing Flat Kit, you'll need to remove already imported Flat Kit from your project, clean all the cache of Unity. It can be found here:

Mac OS: ~/Library/Unity/Asset Store-5.x
Windows: C:\Users\accountName\AppData\Roaming\Unity\Asset Store-5.x

After that restart Unity, open the Package Manager and try importing again.

**Comment by dustyroom-studio** [comment]
Unity issue to track: https://issuetracker.unity3d.com/issues/package-manager-doesnt-show-available-updates.

**Comment by dustyroom-studio** [comment]
The new already released versions of Unity should have this bug fixed.
