### ISSUE TITLE
'Outline Image Effects' does not work in a URP android environment.

### ISSUE THREAD

**Issue by kdy4539** [Dustyroom/flat-kit-doc#100]
**Describe the bug**
I used a translator because I couldn't speak English. 

I applied Cell Shading and Outline Effects to the urp project using 'Styled Surface' data, '[FlatKit] Sample URP Asset', and Image Effects. This worked very well in the editor and window build files, but only the cell shading to which the material was applied worked and the outline effect did not work. I wonder the solution to this.

**Screenshots**
![image](https://user-images.githubusercontent.com/85343537/213866426-60daf766-d19d-4f86-9bcf-231b1068dbf5.png)
![image](https://user-images.githubusercontent.com/85343537/213866444-076ad3fe-d392-425e-a6c2-d5a4f60a3703.png)
![image](https://user-images.githubusercontent.com/85343537/213866465-1cf794fd-a1b9-4b52-a4a2-1b260748d6ca.png)
![image](https://user-images.githubusercontent.com/85343537/213866481-3439842e-3022-4114-acbe-8cff15156d52.png)

**Unity details:**
 - Flat Kit version: [3.2.0]
 - Unity version: [2021.3.11f1]
 - Graphics Pipeline: [URP]
 - URP version (if applicable): [12.1.7]
 - Development OS: [Window 10]

**Build platform:**
 - Platform: [android]
 - Test device: [Galaxy Note10 5G]

**Comment by dustyroom-studio** [comment]
Hi,

If you are using the Outline settings from the Demo scenes, then you will, indeed, have to use the Flat Kit's URP Pipeline Asset Files.

With more recent versions of Flat Kit you have an ability to load it locally on the scene using the [Auto Load Pipeline Asset script](https://flatkit.dustyroom.com/additional-scripts/#auto-load-pipeline-asset). Please, load it as a Component on the Camera object and select the needed _URP Pipeline Asset file_ (the one with the _Renderer_ with the needed _Outline Renderer Feature_ on it).

Alternatively, you can try the older method instead:

1. Set Edit -> Project Settings -> Graphics -> Scriptable Render Pipeline to "[FlatKit] Example Settings URP"
![image](https://user-images.githubusercontent.com/74666746/213867871-561cc7f7-1ceb-4f4e-bb78-4acf12941b5a.png)

2. Set Project Settings -> Quality Settings -> Rendering to "[FlatKit] Example Settings URP" (for all quality settings!)
![image](https://user-images.githubusercontent.com/74666746/213867899-346fcbc9-221c-4348-ad45-6d59aedfc150.png)

If you still have issues with the outlines not appearing in a build, please, let me know the following:
- if your mobile device meets the [requirements](https://flatkit.dustyroom.com/faq/#q-what-is-the-shader-compilation-target-level-of-flat-kit-shaders):
- if there are any errors in the Console;
- if you tried another Unity version

Hope this helps.
