### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by JanPetersCUAS** [Dustyroom/flat-kit-doc#101]
Installed and Imported via Package manager. --> okay
Unpacked the URP --> okay
Select [readme] --> okay
Clicked on "Configure project for" URP --> failed: 

lat Kit] Couldn't load the URP pipeline asset.
UnityEngine.Debug:LogError (object)
FlatKit.ReadmeEditor:ConfigureUrp () (at Assets/FlatKit/Utils/Readme/Editor/ReadmeEditor.cs:317)
FlatKit.ReadmeEditor:OnInspectorGUI () (at Assets/FlatKit/Utils/Readme/Editor/ReadmeEditor.cs:157)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

DEBUG INFO:

Flat Kit version 3.2.0
Unity 2020.3.42f1
Dev platform: WindowsEditor
Target platform: Android
URP installed: True, version 10.10.1
Render pipeline: UniversalPipeline,LightweightPipeline
Color space: Linear
Quality config: UniversalRP-HighQuality
Graphics config: UniversalRP-HighQuality

**Comment by dustyroom-studio** [comment]
Hi,

With more recent versions of Flat Kit you have an ability to load it locally on the scene using the [Auto Load Pipeline Asset script](https://flatkit.dustyroom.com/additional-scripts/#auto-load-pipeline-asset). Please, load it as a Component on the Camera object and select the needed URP Pipeline Asset file (the one with the Renderer with the needed Outline Renderer Feature on it). It looks like this:

![image](https://user-images.githubusercontent.com/74666746/214921288-5bdda802-e7da-4e75-bce6-095ba6f26125.png)

So, you don't have to do the last step from the guide you mentioned. All the Demo scenes load their respective Pipeline Asset files automatically. That last step (clicking the 'Configure project for URP' button) was needed to display the Demo scenes correctly by loading the Pipeline Asset file into the Graphics and Quality settings ( you can find more info about it [here](https://flatkit.dustyroom.com/flat-kit-in-urp/#urp-installation)).

P.S. Could you please let me know where you have found these instructions? I thought I updated where it says "Configure project for URP". The up-to-date installation guide can be found [here](https://flatkit.dustyroom.com/quick-start/).

**Comment by JanPetersCUAS** [comment]
Thanks for the swift feedback. I did see that click in thee inspeczor in the YouTube video which is part of the documentation.
I will give your solution a try tomorrow.

________________________________

**Comment by JanPetersCUAS** [comment]
That was successfull – although the package doesn’t show up in the package manger it seems to have been installed properly.

Von: Dustyroom ***@***.***>
Gesendet: Donnerstag, 26. Januar 2023 19:43
An: Dustyroom/flat-kit-doc ***@***.***>
Cc: Peters Jan ***@***.***>; Author ***@***.***>
Betreff: Re: [Dustyroom/flat-kit-doc] Installation fails (Issue #101)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Hi,

With more recent versions of Flat Kit you have an ability to load it locally on the scene using the Auto Load Pipeline Asset script<https://flatkit.dustyroom.com/additional-scripts/#auto-load-pipeline-asset>. Please, load it as a Component on the Camera object and select the needed URP Pipeline Asset file (the one with the Renderer with the needed Outline Renderer Feature on it). It looks like this:

[image]<https://user-images.githubusercontent.com/74666746/214921288-5bdda802-e7da-4e75-bce6-095ba6f26125.png>

So, you don't have to do the last step from the guide you mentioned. All the Demo scenes load their respective Pipeline Asset files automatically. That last step (clicking the 'Configure project for URP' button) was needed to display the Demo scenes correctly by loading the Pipeline Asset file into the Graphics and Quality settings ( you can find more info about it here<https://flatkit.dustyroom.com/flat-kit-in-urp/#urp-installation>).

P.S. Could you please let me know where you have found these instructions? I thought I updated where it says "Configure project for URP". The up-to-date installation guide can be found here<https://flatkit.dustyroom.com/quick-start/>.
