### ISSUE TITLE
Unity 2022.3.16 URP - opening any demo scene causes crash

### ISSUE THREAD

**Issue by barnim** [Dustyroom/flat-kit-doc#109]
Unity 2022.3.16 URP - opening any FlatKit demo scene causes Unity crash:

![image](https://github.com/Dustyroom/flat-kit-doc/assets/1757395/7b9e6e9d-3a11-4300-8209-202ce66c558c)

FlatKit 4.3.0

**Comment by dustyroom-studio** [comment]
Hi! Thanks for the report. Does it happen when opening the scene `Mugs - Scene1 - OneColorVariousParameters`?

**Comment by barnim** [comment]
Hi! Thx for a quick reply. Unfortunately I removed FlatKit from my project yesterday. I have just reimported it and now the error doesn't occur. I can open all demo scenes. I havn't changed anything in my project apart from adding and removing just a few prefabs in one of my scenes. Let's hope it was sth related to the "humor" of my instance of Unity.

**Comment by dustyroom-studio** [comment]
Good to know the issue disappeared. Please let us know if it occurs again.
