### ISSUE TITLE
Multiple error messages when initially importing Flat kit.

### ISSUE THREAD

**Issue by zSquidge** [Dustyroom/flat-kit-doc#11]
Hi, when importing and unpacking flat kit I receive 45 error messages and am unable to drag and drop the package into the render pipeline settings. I have used Unity 2020.2.1, 2020.1.6, 2019.4.1 and have even booted up a brand new project to try get it working.

When using the Built-In pipeline I do not get the error messages but, I am still unable to drag and drop the package into the render pipeline settings.

Do you know why this could be? I assume I'm missing something that may be obvious to someone else, any help is greatly appreciated!

**Comment by dustyroom-studio** [comment]
Hi,

Could you please copy at least a few of the errors? A screenshot of the Console or a copied text would be useful.

Before dragging the settings file into Graphics and Quality tabs, please make sure you have unpacked the unitypackage you downloaded from Package Manager, described in the installation guide on the step 2 [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)

In Built-In Rendering Pipeline you don't have to drag and drop the settings files as you would do in URP. But you'll need to unpack Built-In RP files, just like in URP. It is described in the manual's [quick start guide](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit). You choose your RP version on the step 2.

Looking forward to your reply.

**Comment by zSquidge** [comment]
> Hi,
> 
> Could you please copy at least a few of the errors? A screenshot of the Console or a copied text would be useful.
> 
> Before dragging the settings file into Graphics and Quality tabs, please make sure you have unpacked the unitypackage you downloaded from Package Manager, described in the installation guide on the step 2 [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)
> 
> In Built-In Rendering Pipeline you don't have to drag and drop the settings files as you would do in URP. But you'll need to unpack Built-In RP files, just like in URP. It is described in the manual's [quick start guide](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit). You choose your RP version on the step 2.
> 
> Looking forward to your reply.

Here's a screenshot of the errors I receive when using the URP, thanks for the quick response!
(https://user-images.githubusercontent.com/44914416/104893715-bc1b0100-59ae-11eb-9819-87d93d904dbf.PNG)

**Comment by dustyroom-studio** [comment]
Thank you for the screenshot.

To confirm, you are trying to import Flat Kit into a freshly created **URP** project in Unity (various versions), correct?
Like this
![new-urp-project](https://user-images.githubusercontent.com/74666746/104896160-6ed36b00-597f-11eb-86e2-7b8ab2e649b5.png)

If so then:
- Could you please let me know what version of Universal RP you are using? You can check it in Window -> Package Manager
- Have you unpacked **[Render Pipeline] Universal (URP).unitypackage**?
- Please confirm you have tried importing Flat Kit according to the guide [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit).

If you are creating the Built-In project (known as '3D') like here:
![new-3d-project](https://user-images.githubusercontent.com/74666746/104896081-54998d00-597f-11eb-9ad7-a84bc6d1698a.png)
...then you'll need to import the Built-In version of Flat Kit, not the URP version. It is also described in the guide [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit).

**Comment by zSquidge** [comment]
Alright, turns out my project wasnt in URP, this has fixed it for me! Thank's heaps for helping out with it!
