### ISSUE TITLE
Stylised Surface causes an error in Unity 6.0 and turns material pink:

### ISSUE THREAD

**Issue by laurensvo92** [Dustyroom/flat-kit-doc#111]
**Describe the bug**

Stylised Surface causes an error in Unity 6.0 and turns material pink: 

Shader error in 'FlatKit/Stylized Surface': undeclared identifier '_FOVEATED_RENDERING_NON_UNIFORM_RASTER' at Clocktower/Library/PackageCache/com.unity.render-pipelines.core/ShaderLibrary/FoveatedRendering.hlsl(27) (on metal)

Compiling Subshader: 0, Pass: ForwardLit, Vertex program with _FORWARD_PLUS _MAIN_LIGHT_SHADOWS
Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_NEEDS_RENDERPASS_FBFETCH_FALLBACK UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
Disabled keywords: DIRLIGHTMAP_COMBINED DR_VERTEX_COLORS_ON DYNAMICLIGHTMAP_ON FOG_EXP FOG_EXP2 FOG_LINEAR INSTANCING_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING SHADER_API_GLES30 SHADOWS_SHADOWMASK UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHTS_VERTEX _CLUSTERED_RENDERING _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN _NORMALMAP _RECEIVE_SHADOWS_OFF

**To Reproduce**
1. Install Unity version 6.0
2. Choose any material
3. go to the inspector and select "FlatKit > Stylized Surface. 
4. See error and screenshot.

**Expected behavior**
I woud not expect to see an error and the material to go pink.

**Screenshots**

Flat Kit version 4.5.0
Unity 6000.0.0b13
Dev platform: OSXEditor
Target platform: StandaloneOSX
URP installed: True, version 17.0.2
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: PC_RPAsset
Graphics config: PC_RPAsset

**Additional context**
![Scherm­afbeelding 2024-04-04 om 15 30 12](https://github.com/Dustyroom/flat-kit-doc/assets/30549251/2e8d18ae-1da2-4bd2-a0ec-86f28beee9e9)

**Comment by dustyroom-studio** [comment]
Hi! Unfortunately we can't support beta versions of Unity as they only let us upload files for released versions of the editor.
