### ISSUE TITLE
Pink shader on android

### ISSUE THREAD

**Issue by ifunface** [Dustyroom/flat-kit-doc#12]
Everything was working good... Then I upgraded from 2020.1 to 2020.2. Its working in editor but I got pink texture on android device. Tried to add the shader in the list of always include but it give an error about too many shader variant... Ive tried to re-download and re-install flatkit without success. Tried to delete library too... Didnt work

**Comment by dustyroom-studio** [comment]
Please let us know some details help with debugging:
- Rendering Pipeline used (and URP version if applicable):
- Exact Unity version:
- Android version and device model:
- Any errors or warnings in the Unity Console:
- Any runtime errors in `logcat`:
- Development OS:
- Does the issue happen with a scene included in Flat Kit?

**Comment by dustyroom-studio** [comment]
This should be fixed in the latest version of Flat Kit.

**Comment by hooman-zakikhani-nezhad-arange** [comment]
same result here ! any suggestion ?

**Comment by dustyroom-studio** [comment]
Please let us know some details help with debugging:

    Rendering Pipeline used (and URP version if applicable):
    Exact Unity version:
    Android version and device model:
    Any errors or warnings in the Unity Console:
    Any runtime errors in logcat:
    Development OS:

To find out this info, please, locate the [Readme] file in Assets/Flat Kit, press Copy debug info and paste it here.

Does the issue happen with a scene included in Flat Kit?

Also, have you set up Flat Kit for URP (if using in URP)? To do this, locate the [Readme] file in Assets/Flat Kit and press 'Configure project for URP' button.
