### ISSUE TITLE
Use normals for outlines per object

### ISSUE THREAD

**Issue by nsinghsingh** [Dustyroom/flat-kit-doc#122]
I want to set outlines for each object so I can control the color of each object's outline individually. The main problem is that I can't seem to use normals for the outlines per object.

The global outline effect is capable of doing that with no problem as seen here

![image](https://github.com/user-attachments/assets/31bbdbd3-79c1-4d9c-a4d3-5ff5ca183bbd)

And the per object outline ends up looking like this

![image](https://github.com/user-attachments/assets/0f91d6a5-b9b6-4bb5-9230-d03fc1ed1b25)

Is this possible?

**Comment by vdzitsiuk** [comment]
It's impossible to do with Flat Kit out of the box unfortunately. The workarounds may be very time consuming and/or not very performance-friendly. 

The two outlines are very different in their nature.
I suggest you reading the chapters in case you haven't:

Object-based outline:
https://flatkit.dustyroom.com/stylized-surface/#outline

Outline Image Effect:
https://flatkit.dustyroom.com/outlines/

**Comment by nsinghsingh** [comment]
I see, I'll rethink my project then
