### ISSUE TITLE
Exclude water from outline

### ISSUE THREAD

**Issue by nsinghsingh** [Dustyroom/flat-kit-doc#123]
I'd like the water to not have outlines

![image](https://github.com/user-attachments/assets/dd63b4bc-d209-459b-a9c9-e9fb1d2cb868)

The areas without ground underneath show without outline but I need the ground there.

I tried looking in the documentation but it only specifies the Stylized Surface Shader and not the Water Shader.

![image](https://github.com/user-attachments/assets/001446f8-02db-4b4f-95c9-eec4b7abce7e)

**Comment by vdzitsiuk** [comment]
You can set the Water to transparent rendering mode as well.

![water shader render modes](https://github.com/user-attachments/assets/624d182c-2fd6-4bcc-b547-8ff488b5d448)

Then you need to set the outlines to be rendered before transparents (see 'Render Event' in the doc: https://flatkit.dustyroom.com/outlines/#advanced-parameters)

**Comment by nsinghsingh** [comment]
That worked. I did have to run the scene in order for the outline to update in the scene view though.
