### ISSUE TITLE
Stylizedoutline shader doesn't work with other shaders using depth, while just Stylized shader does.

### ISSUE THREAD

**Issue by Jointy87** [Dustyroom/flat-kit-doc#14]
Hi there,

You can read the full problem description here: https://forum.unity.com/threads/getting-fog-shader-to-work-correctly-in-combination-with-a-cell-outline-shader.1022509/?fbclid=IwAR2O7I5z5aRppdER7DDawrDQ_PtKcUo2UBDlKWxnwe--KIG0bqRPQIvEN2E

I've asked someone I know who knows about shaders and according to him there's no reason why this shouldn't work. And as a matter of fact, it DOES work if I just use the Stylized shader without outline, but when I use the one with outline, it won't work. I'm hoping it's a small bug/oversight that can be fixed, instead of it being the intended behavior. My friend mentioned something about depth buffer? As you can tell I myself am NOT AT ALL at home at shaders haha.

Hope you guys can have a look at this and hopefully make it work :) Thanks!

**Comment by dustyroom-studio** [comment]
Hello,

Can this issue be reproduced in one of the demo scenes included with Flat Kit?

Also, are you using the standard Unity fog, or the image effect fog from Flat Kit?

**Comment by Jointy87** [comment]
Hiya,

The mist is neither a Unity fog or the fog from Flat Kit. I can't get those options to work well because I'm using orthographic camera. The fog I'm using is a plane with a shader. You can see how I made it in the post linked above. There should be no reason that shader wouldn't work together with flatkit. As a matter of fact, it DOES work with your stylized shader without outline, but not with your stylized shader with outline. I'm hoping I can get it to work, seeing as how other conventional fog options are a no go because I'm using orthographic. Unless you have a way to get your fog to work well with orthographic?

Thanks.

**Comment by dustyroom-studio** [comment]
Can you please try using the `LightPlane` shader that comes with Flat Kit for the fog? Does it have the same issue with the outlines?

**Comment by Jointy87** [comment]
Heya,

Sorry for the late reply. I've tried the LightPlane shader and here are the results:

![FlatKit Shader Test Perspective Cam](https://user-images.githubusercontent.com/5092172/116052446-ea793e00-a679-11eb-8188-cf554203332a.png)
![FlatKit Shader Test Orthographic Cam](https://user-images.githubusercontent.com/5092172/116052459-ecdb9800-a679-11eb-929a-c777989d77a5.png)

As you can see the LightPlane shader works fine if your camera is set to perspective and if you're not using an outline. But if the camera is set to orthographic, the LightPlane shader doesn't work very well at all.

**Comment by dustyroom-studio** [comment]
Hi, Could you please let me know the folllowing:
- the version of Unity
- the version of Universal RP
- the version of Flat Kit
You can find all the info at once in our Flat Kit Readme tool  (Project panel -> Assets -> Flat Kit -> Readme file. Please, select it and send me the screenshot).  

![flat-kit-readme-screenshot](https://user-images.githubusercontent.com/74666746/116241986-2261ad80-a76e-11eb-9ccb-32607e7adc5b.png)

If you don't see Readme, then you most likely have an old version of Flat Kit. If so, here's what to do:

- Delete Flat Kit from your current project (Project panel -> Assets)
- Update Unity to the latest 2019 version (currently it is 2019.4.25f1) using Unity Hub.
- Create / open a URP project in the newly installed version of Unity
- Go to Window -> Package Manager -> 'Packages: My Assets' drop down menu -> Flat Kit -> Update button.
If you don't see or can't press 'Update' or 'Download', please, delete the Package Manager cache:
_Mac OS: (press Shift+Cmd+G in any Finder Window and paste this path)_
~/Library/Unity/Asset Store-5.x
_Windows: (replace accountName with your actual account name)_
C:\Users\accountName\AppData\Roaming\Unity\Asset Store-5.x)
- Finish installing Flat Kit as described [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit) in the video or in the written guide below the video. Specifically, the steps 5 and 6 where it is saying about [Flat Kit] Example Settings URP file in Graphics and Quality tabs for all quality levels.

**Comment by Jointy87** [comment]
Hey, thanks for the reply.

I didn't have the read-me file. So I deleted Flat Kit and will install again. A bit dumb of me: I forgot to make note of what version of Flat Kit it was before deleting. But as it didn't have a read-me it's apparently too old anyway, right?

The Unity version I'm using is 2020.1.17f1. The URP version is 8.3.1 according to my package manager. You say I should upgrade my Unity to the latest 2019 version. But for me that would be a downgrade. Is my version ok?

I've downloaded the latest Flat Kit version (2.1.8), imported it according to instructions. But the same problem as stated above remains I'm afraid.

**Comment by dustyroom-studio** [comment]
Correct, the absence of a Readme file most likely means a too old version of Flat Kit.

You'll need to update Unity to the latest major version you are working on. For example, if you work in **2019**.x.x, you'll need to update to **2019**.4.25f1. If you work in **2020**.x.x (you said 2020.1.17f1), please update to **2020**.3.6f1.
These suggested versions are currently the latest ones. This is a [Unity's Package Manager bug](https://issuetracker.unity3d.com/issues/package-manager-doesnt-show-available-updates), which they had in earlier versions of Unity, including yours. As soon as you update Unity to a working version, clean the cache (please, see the guide in my previous reply), update Flat Kit to 2.1.8, and finish installing Flat Kit as described / shown [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit), you should be able to download Flat Kit and other affected assets, in case you use any.

If you for some reason Unity still won't let you update to 2.1.8, drop a mail to info@dustyroom.com, I'll send you the direct link to Flat Kit.

**Comment by dustyroom-studio** [comment]
Please re-open the issue if it hasn't been resolved.
