### ISSUE TITLE
Shader not working in build, works in editor

### ISSUE THREAD

**Issue by mattrochon** [Dustyroom/flat-kit-doc#16]
When i do a build of my project the objects on which I have used the stylized surface w/ outline shaders are colored pink. In the log file I see the following error:

ERROR: Shader FlatKit/Stylized Surface shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader FlatKit/Stylized Surface With Outline shader is not supported on this GPU (none of subshaders/fallbacks are suitable)

I find this unlikely however, as I am running this on a brand new RTX 3090

![image](https://user-images.githubusercontent.com/1702787/106396080-c20fd980-63d3-11eb-81b3-28ba0add7fc1.png)

**Comment by dustyroom-studio** [comment]
If you're experiencing this issue in the builds only, and in the editor it looks correct, we've just sent an update that targets this issue to Unity for the review. If you would like to try it before it is released, please send me an email to info@dustyroom.com, and I'll send you the pack directly.

If that's not the case, please include the details like Unity version, Flat Kit version and rendering pipeline. Preferable, with screenshots of your Package Manager with Flat Kit selected, Graphics settings, Quality settings tabs — anything you think may help me reproduce your issue.

**Comment by mattrochon** [comment]
If its already submitted for review I can wait. I will try it out when you
publish the update

**Comment by dustyroom-studio** [comment]
The update is live! Thank you for your patience.
Please re-open the issue if for some reason this still occurs.
