### ISSUE TITLE
Warning message: [FlatKit] Missing Outline Settings

### ISSUE THREAD

**Issue by gflores** [Dustyroom/flat-kit-doc#17]
![image](https://user-images.githubusercontent.com/1119607/106886163-8bf98f00-671e-11eb-9208-1ac81d08ab1f.png)

It also might be related but the shader Stylized Surface With Outline doesn't appear in /FlatKit

![image](https://user-images.githubusercontent.com/1119607/106886244-a16eb900-671e-11eb-8f4a-df7ac8bcba9e.png)

Instead it appears in "Failed to compile"
![image](https://user-images.githubusercontent.com/1119607/106886285-aaf82100-671e-11eb-84f5-ca3fa0414455.png)

**Comment by dustyroom-studio** [comment]
Please, re-import Flat Kit.
If you are using Unity 2019.1.x, there is a bug with Unity's Package Manager, which messes up the assets version for Unity 2019.1.x users, and sometimes 2020.x users, you theoretically can have the older version of the asset than it is stated in the Package Manager (you see one version in Package Manager but in reality you've got an older one). But it is still possible to get the later version of Flat Kit.
**Here's how to clean the cache**
https://flatkit.dustyroom.com/#q-i-am-trying-to-import-flat-kit-but-cant-find-urp-package--it-downloads-old-version-of-flat-kit
**Here's how to install Flat Kit after cleaning the cache**
https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit

**Comment by dustyroom-studio** [comment]
Please re-open the issue if it's not resolved.
