### ISSUE TITLE
Outline not working on edges

### ISSUE THREAD

**Issue by gflores** [Dustyroom/flat-kit-doc#18]
Check out the left and right edges of this box:
![image](https://user-images.githubusercontent.com/1119607/106886467-e2ff6400-671e-11eb-964d-12c3796045ed.png)

**Comment by dustyroom-studio** [comment]
This is a normal behavior. To reduce the gaps:
- Smoothen the edges. If the model has to have hard edges, adjust Smoothing Angle parameter in the model's Import Settings tab
https://flatkit.dustyroom.com/FlatKit_Manual_Images/mesh-import-settings.png
- Have a more polygonal model
- Try adjusting Camera Distance parameter on the shader in conjunction with the camera distance itself.

**Comment by gflores** [comment]
How come those two youtube videos are able to solve this problem in less than 5minutes:

[https://youtu.be/1QPA3s0S3Oo?t=217](https://youtu.be/1QPA3s0S3Oo?t=217)

[https://www.youtube.com/watch?v=X-kaX_8bYRc](https://www.youtube.com/watch?v=X-kaX_8bYRc)

Can you add the fix too please ?

**Comment by dustyroom-studio** [comment]
Setting the scale of the extruded object for the outline is going to work in very rare cases, like the simple cube in the video example. It will not work well on more complex objects, especially with non-convex geometry.
We can add the scale parameter to the outline shader, but it's unlikely that the increased complexity of tuning the materials is worth the limited use case.
![image](https://user-images.githubusercontent.com/74666746/107109502-eca7cb00-67f5-11eb-8620-9460526b8e1b.png)
