### ISSUE TITLE
Water shader not working properly in Game view

### ISSUE THREAD

**Issue by PowerZox** [Dustyroom/flat-kit-doc#19]
The URP Water Shader does not work properly in Game view when using Perspective Camera. It does however work in Scene view or when using Orthographic Camera.

This is in Game view:
![game view](https://user-images.githubusercontent.com/68038592/107159497-6ce94000-695e-11eb-8334-ec6a7a69c0f2.PNG)

And this in Scene view:
![scene view](https://user-images.githubusercontent.com/68038592/107159484-59d67000-695e-11eb-9892-916e35b94d56.PNG)

**Comment by dustyroom-studio** [comment]
Hi,
- What version of Unity and Flat Kit are you using?
- Are there any errors in Console?
- Do the demo scenes ('Ocean' or 'Pool') work correctly? If yes, how to reproduce your issue?

**Comment by PowerZox** [comment]
- Unity 2019.4.19f1 and the latest version of Flat Kit.
- No errors in the console
- The demo scenes do work correctly. To reproduce the issue I create a new scene, create a new material with the water shader on it and assign it to a plane in the scene.

**Comment by PowerZox** [comment]
Updating my project to Unity 2020.2 fixed my issue
