### ISSUE TITLE
Water shaders look completely different from sample video (URP)

### ISSUE THREAD

**Issue by spvn** [Dustyroom/flat-kit-doc#2]
Hi I just bought your asset and hope this is the right place to report an issue. This is what my water demo scene looks like. I have not made any changes since importing the asset. As you can see, the objects in the top row aren't even transparent like in the demo video I saw on the asset store page.

![image](https://user-images.githubusercontent.com/5820312/100617293-45219e80-3355-11eb-8d0a-00bbdc0098fb.png)

I'm using Unity 2019.4.1f1, and am on URP 7.3.1, version 2.0.6 of your asset. Any idea what's causing this problem?

**Comment by dustyroom-studio** [comment]
Thank you for reporting the issue. We'll look into it and write back.

**Comment by dustyroom-studio** [comment]
Could you please navigate to Project Settings -> Graphics and insert **[FlatKit] Example Settings URP** file into **Scriptable Rendering Pipeline Setting** field.
Please, do this in Quality tab's **Rendering** field as well. Let us know if it still don't work.

**Comment by spvn** [comment]
Adding it to Graphics tab only did not work, but it worked once I added it to Quality tab as well. May I know what are the important settings to change from the default URP render pipeline asset to make the water shaders look correct?

Also, how viable are these water shaders on mobile in your opinion (when used sparingly)?

Thanks a lot for the reply.

**Comment by dustyroom-studio** [comment]
In the Universal Rendering Pipeline Asset settings, there should be _Depth Texture_ and _Opaque Texture_ turned on. These settings are off by default.

The water shader should work well on mobiles. If you've got an issue with getting it to work with mobiles, send us a message to info [at] dustyroom [dot] com

**Comment by spvn** [comment]
Sorry to add on but I've realised that the water shader doesn't work with an Orthographic camera... I didn't see this limitation stated anywhere in the documentation. Slightly disappointed about that... It looks ok in the scene view but is broken in Game view. I'm guessing this is an unfortunate limitation of the shader?

![image](https://user-images.githubusercontent.com/5820312/100769172-a5d4d800-3436-11eb-8a12-47564aaa2c93.png)

**Comment by dustyroom-studio** [comment]
This must be a bug with the water shader, we weren't aware it fails with an ortho camera.
We'll take a look and update here.

**Comment by Jointy87** [comment]
Hiya, 

Very glad to see you guys are working on an update on this. Do you perhaps have a rough ETA on when you believe this update will go live? And when it goes live, I can just update it via my Package Manager as per usual? 

Thank you for your time and effort on this. Cheers,

**Comment by vdzitsiuk** [comment]
Hi, it's really hard to say what time it will take but it is a high priority one, so it shouldn't take long.
And yes, there will be a notification about a free update in Package Manager.

**Comment by dustyroom-studio** [comment]
Hi, it's really hard to say what time it will take but it is a high priority one, so it shouldn't take long.
And yes, there will be a notification about a free update in Package Manager.

**Comment by Jointy87** [comment]
Thanks :)

**Comment by dustyroom-studio** [comment]
This should be now fixed in Flat Kit 2.0.6.
Please re-open the issue if it is not resolved.
