### ISSUE TITLE
Stylized surface shader and Ambient Occlusion

### ISSUE THREAD

**Issue by molleindustria** [Dustyroom/flat-kit-doc#20]
The URP now ships with a screen based [ambient occlusion render feature](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@10.0/manual/post-processing-ssao.html)

It looks like the stylized surface shader doesn't support it. When activated it makes flat shaded objects translucent if source is "depth normals" or unaffected by AO if source is "depth". It also kills the flat kit fog. 
Image below, the darker object in the background has a standard material affected by AO:
![Image 004](https://user-images.githubusercontent.com/12369651/109062981-9d4b1100-76b6-11eb-88fd-281abdf6eae5.png)

I tried adding the depth normals feature but the result is the same.

I know it's a new feature but cartoon shading and AO go well together.

**Comment by dzitsiuk** [comment]
Thank you for bringing this up.
We are planning to add support to the new AO in a future update to Flat Kit. Stay tuned.

**Comment by dustyroom-studio** [comment]
Thank you for starting the issue.
We are planning to add support to the new AO to Flat Kit in a future update.
Stay tuned.

**Comment by molleindustria** [comment]
Browsing through Unity shader sources I found this page that might offer some starting points
https://github.com/Unity-Technologies/Graphics/blob/d73079e2b43ee22ae2cb989620c6298fd4a9c9a8/com.unity.render-pipelines.universal/Documentation~/upgrade-guide-10-0-x.md

**Comment by dustyroom-studio** [comment]
We've added SSAO support to Flat Kit, it will become available in the next update which should be in the Asset Store next week.

**Comment by dustyroom-studio** [comment]
The update with SSAO support is now live in the store.
