### ISSUE TITLE
Have Unlit and Lit version for the shaders [URP]

### ISSUE THREAD

**Issue by mickplouffe** [Dustyroom/flat-kit-doc#21]
Hi!

I stumble on this little problematic, that is the shaders are for the most part Unlit. No Problem for Static light, but is a problem is there is a day/night cycle. Saddly I don't currently understand Scripted Shaders to add Lit feature.

Is it possible to make both version availible? (In URP)

Thanks.

**Describe the solution you'd like**
Adding the option or separted shader for Unlit and Lit material.

**Additional context**
It feel weird that the water still glow at night.

**Comment by dustyroom-studio** [comment]
Hi, thank you for reporting these.
We already have plans to add an ability for the Water shader to react on the light in one of the future updates.
All the shaders are lit, despite the fact that the Water shader looks like unlit. The water is a bit more complex than just lit/unlit shader.

**Comment by mickplouffe** [comment]
Thanks for the quick answer!

Yup. I looked up in the water shader and I am not qualified to make it react to the light. Really seems more complexe as you say.

I am looking forward the update ! (Anyway my game don't go release before.... 2025 ish so...)

**Comment by dustyroom-studio** [comment]
We have added a "Light Color Contribution" parameter to the water shader to address this issue.
The parameter controls the impact of the main scene light on the water color. This is also affected by the light intensity, so it should work for the day/night cycle.

**Comment by dustyroom-studio** [comment]
This change will be part of the 2.1.6 update.
