### ISSUE TITLE
Outline Image Effect - VR Single Pass Support

### ISSUE THREAD

**Issue by TrueBeef** [Dustyroom/flat-kit-doc#24]
Hey guys, me again. Im attempting to make the image effect for the outlines work in VR with the single-pass instanced rendering mode. I've tried a couple solutions using the Unity documentation on the subject ([specifically this one](https://docs.unity3d.com/Manual/SinglePassStereoRendering.html)) though nothing seems to stick. Currently, the game view simply renders a gray/black view with nothing else visible.

I've tried adjusting the UV Coords with the `unity_StereoScaleOffset` and the `UnityStereoTransformScreenSpaceTex`, but I believe I am simply too inexperienced to understand how to use these in order to get the desired results.

Below is an example of what is being rendered (Scene view vs Game view). In the headset, the left eye renders a white image, and the right eye renders a black one.

![image](https://user-images.githubusercontent.com/11018765/111054821-96e1c680-8424-11eb-8bf2-a7f18c385f04.png)

This is the outline settings currently:

![image](https://user-images.githubusercontent.com/11018765/111054881-e6c08d80-8424-11eb-9406-2fe384afeca7.png)

For additional context, I am using a valve index headset with Steam VR Unity plugin.

Also, thanks for the great asset! Appreciate all the help with this VR stuff.

**Comment by dustyroom-studio** [comment]
Thank you for the details description and the screenshots.

#### A few questions to help us debug:
1. Which version of Unity are you using?
1. Which version of URP are you using?
2. Can you please list the steps to reproduce the issue from a blank project to the screen you're seeing?

**Comment by dustyroom-studio** [comment]
Hi! We have added Single Pass Stereo support for Unity 2021 and later in Flat Kit 2.9.0, please check it out.
