### ISSUE TITLE
Water shader ignores standard fog

### ISSUE THREAD

**Issue by molleindustria** [Dustyroom/flat-kit-doc#27]
![Image 062](https://user-images.githubusercontent.com/12369651/111483729-714a0b00-870b-11eb-92ae-5c499653b17b.png)

I really like the flat kit water shader but is there a way to make it work with the standard unity Fog? Image above.

**Comment by dustyroom-studio** [comment]
This should be fixed in the next release of Flat Kit (2.1.6) which should appear on the Asset Store next week.

**Comment by dustyroom-studio** [comment]
The fix is now live in the store.
