### ISSUE TITLE
URP , FOG SCRIPT AND OUTLINE CAN'T BE FOUND

### ISSUE THREAD

**Issue by Delrey27** [Dustyroom/flat-kit-doc#29]
AFTER UPDATING TO UNITY 2020 I GOT THE URP VERSION TO WORK, but now i have the scripts of fog and outline missing somehow, the weird part is that they are applied in the valley scene but are not showing on inspector when clicking camera.
![image](https://user-images.githubusercontent.com/80860089/111579250-fbe74480-87b5-11eb-8c3c-7c29e0a54a2b.png)

when i added a new camera and tried to attach the fog script to it here's what happened 
![image](https://user-images.githubusercontent.com/80860089/111579193-dce8b280-87b5-11eb-93d1-4de7ef034970.png)

also when i try to look for it from the inspector it doesn't show up
![image](https://user-images.githubusercontent.com/80860089/111579233-f25ddc80-87b5-11eb-8586-9d4233f997a0.png)

**Comment by dustyroom-studio** [comment]
Hi,

In Built-In RP the post effects are the Components on a camera.

If you use the URP, the post effects are the Renderer Features found in URP Forward Renderer. If you find the Valley Forward Renderer, you'll see the Fog Renderer Feature on it.

**Comment by Delrey27** [comment]
can you please show me how i can attach it to my camera, in a different scene that i have

**Comment by Delrey27** [comment]
![image](https://user-images.githubusercontent.com/80860089/111607678-c56ef100-87d8-11eb-912c-ae7d46311c12.png)

i did tweak the gradients on this settings yet nothing changed in the scene, id be grateful if you walked me through how to use these step by step thank you very much

**Comment by dustyroom-studio** [comment]
1. Set **[Flat Kit] Example Settings URP** in Edit -> Project Settings -> **Graphics** window

![graphics](https://user-images.githubusercontent.com/74666746/111613955-bd6a7d80-87e7-11eb-8cc7-35e63f1c98a4.png)

2. Set **[Flat Kit] Example Settings URP** in Edit -> Project Settings -> **Quality** window for all Quality Levels

![quality](https://user-images.githubusercontent.com/74666746/111613998-c78c7c00-87e7-11eb-83df-c9570722d341.png)

This is described in the installation guide in the Manual [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit).

3. Do a search in the Project tab for the word "Valley". Locate **[Flat Kit] Valley-FogSettings** file. For each demo scene where the fog is used we added its own Forward Settings. 

![valley search](https://user-images.githubusercontent.com/74666746/111614244-08849080-87e8-11eb-8070-874558359d07.png)

4. Look at the Inspector panel when you have **[Flat Kit] Valley-FogSettings** file selected. You can tweak these parameters and you'll see the changes on the scene. Please, make sure to launch the scene, sometimes the effect takes place when you press Play.

![valley inspector](https://user-images.githubusercontent.com/74666746/111614545-631dec80-87e8-11eb-80be-9857b085e896.png)

**Comment by dustyroom-studio** [comment]
Please re-open this issue if it hasn't been resolved.
