### ISSUE TITLE
Water Shaders Missing from 2.0.6 Package

### ISSUE THREAD

**Issue by chriszumberge** [Dustyroom/flat-kit-doc#3]
Purchased on the Asset Store, downloaded via the package manager, imported the [Render Pipeline] Built-In package.
The Pool and Ocean Water demos are also missing.

**Comment by dustyroom-studio** [comment]
Hi, thank you for buying Flat Kit. The Water shader is available for URP only. Could you please try importing it into the URP project?

**Comment by chriszumberge** [comment]
Done, thanks. I did not see that outlined in the documentation and the caveats that the package was created for built-in made it seem like the built-in renderer package would have the best compatibility and most assets.
