### ISSUE TITLE
LightPlane shader isn't visible on Oculus Quest 2

### ISSUE THREAD

**Issue by mutp** [Dustyroom/flat-kit-doc#30]
**Describe the bug**
A material created using LightPlane shader doesn't render/isn't visible on Oculus Quest 2. 

**To Reproduce**
1. Create Material with LightPlane shader
2. Apply on any mesh
3. View apk on Oculus Quest 2
4. Mesh not visible

**Expected behavior**
Mesh should be visible on Oculus Quest 2 with LightPlane shader on it.

**Unity details:**
 - Flat Kit version: 1.5.5
 - Unity version: 2019.3.11f1
 - Graphics Pipeline: Bult-in
 - Development OS: Windows

**Build platform:**
 - Platform: Android
 - Test device: Oculus Quest 2

**Comment by dustyroom-studio** [comment]
Hi,

Could you please create the project in URP and update to the latest Flat Kit (currently it's v. 2.1.5)?
From Unity's 2021 public roadmap ([https://blogs.unity3d.com/2020/08/13/the-road-to-2021/](https://blogs.unity3d.com/2020/08/13/the-road-to-2021/)) it seems that the Built-in RP is not being developed and will become obsolete it in the future. As a small studio, unfortunately we can't spend our time supporting a deprecated RP.
Please let us know (write an email to info@dustyroom.com) if this is critical for your project. If you need to work in Built-In RP and can't update to the latest Flat Kit, we're offering you a refund.

**Comment by mutp** [comment]
Hello, I will try v2.1.5 asap but unfortunately, I can't move to URP as the game has been built on built-in. I will test the latest version and get back to you.

**Comment by mutp** [comment]
I can confirm that it doesn't show up on v2.1.5 either (built-in).

**Comment by dustyroom-studio** [comment]
Thank you for confirming. Please, write an email to info@dustyroom.com and I'll request a refund for you.

**Comment by mutp** [comment]
Oh no, I love the asset too much so I don't want a refund. :) I'll try to make it work or find another solution. Thanks for the help!
