### ISSUE TITLE
Can't view object graphical thumbnails while Outline is enabled in URP

### ISSUE THREAD

**Issue by r0ckl0bsta** [Dustyroom/flat-kit-doc#33]
**Describe the bug**
While the New Flat Kit Outline renderer feature is enabled in URP, any visual thumbnails (ie. materials, models, and prefabs) are not displayed in the Preview window or Project window thumbnail. Instead, both the preview window and the project thumbnail default to a capture of my Scene view.

**To Reproduce**
1. Create and assign a new URP Renderer with the New Flat Kit Outline render feature added and enabled.
2. Reimport any visual asset, such as model. 
3. Note that selecting that asset does not display its thumbnail in the preview window nor as a thumbnail in the Project folder view.
4. To test, disable the New Flat Kit Outline render feature and reimport the asset in question, and note the thumbnail/preview.

**Expected behavior**
Thumbnails and Previews should be properly represented when this render feature is enabled.

**Screenshots**

With Outline enabled:
![image](https://user-images.githubusercontent.com/79990644/113494847-6983b800-94ba-11eb-9b71-6be72f9e0295.png)
![image](https://user-images.githubusercontent.com/79990644/113494871-ab146300-94ba-11eb-80b7-aed325fd69ae.png)

With Outline disabled:
![image](https://user-images.githubusercontent.com/79990644/113494848-71dbf300-94ba-11eb-8205-fb7feae7403c.png)
![image](https://user-images.githubusercontent.com/79990644/113494869-9d5edd80-94ba-11eb-9e6d-518eccac8b7d.png)

**Unity details:**
 - Flat Kit version: 2.1.6
 - Unity version: 2020.1.13f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 8.2.0
 - Development OS: Windows 10
 - Post Processing: 3.1.0

**Build platform:**
 - Platform: Oculus Quest (testing in desktop mode)
 - Test device: Quest 2

**Comment by dustyroom-studio** [comment]
Unfortunately we can't reproduce this issue in our testing.

This seems like a bug with Unity, since there is no way we can control asset previews with the render passes.

A few questions to help us debug:
- Does this happen in Unity 2021?
- Does it happen when build target is set to desktop?
- Does it happen on a vanilla project with Flat Kit imported, on a scene imported with Flat Kit?

**Comment by r0ckl0bsta** [comment]
Tested on the version of Unity mentioned in the ticket (2020.1.13f1) with everything identical excluding XR supports, and cannot reproduce either. I'll end up troubleshooting this on my own and will share if I find anything conclusive. 

Thanks!
