### ISSUE TITLE
OpenXR Camera renders grey/black eyes with FlatKit Fog in Single Pass Instanced rendering mode

### ISSUE THREAD

**Issue by albrrt** [Dustyroom/flat-kit-doc#35]
**Describe the bug**

The camera doesn't render the scene if we activate the Flat Kit Fog effect in the [FlatKit] Example Forward Renderer.
The left eye is grey and the right eye is black.

**To Reproduce**

- Create a new project (Unity 2020.3.3f1) with the URP template (URP v.10.4.0)
- Import the OpenXR Plugin (v.1.0.3)
- Also import the "Controller" samples of the OpenXR Plugin
- Setup the OpenXR plugin to work with HTC Vive
   - Edit > Project Settings > XR Plug-in Management > Plug-in Providers > Tick the "OpenXR" box
   - Click on the red warning icon which appears next to "OpenXR"
   - Click "Fix All"
   - To Fix the remaining issue go to Edit > Project Settings > XR Plug-in Management > OpenXR > Features and tick the box for the HTC Vive Controller Profile
    - Close the window

- Test the OpenXR scene: navigate to Assets > Samples > OpenXR Plugin > 1.0.3 > Controller > ControllerSample.unity and open the scene.
- Hit Play : the scene is rendered correctly in the VR headset

- Import the FlatKit package (v.2.1.6)
- Import the FlatKit URP Package
- Setup the SRP Settings : Edit > Project Settings > Graphics > change the the "Scriptable Render Pipeline Settings" to "[FlatKit] Example Settings URP"
- Edit > Project Settings > Quality > change the "Rendering" to "[FlatKit] Example Settings URP".
- At this stage, the OpenXR sample scene is still working correctly.
- Activate the FlatKit Fog: Assets > FlatKit > [Render Pipeline] URP > Example Settings > [FlatKit] Example Forward Rederer.asset and activate the "Flat Kit Fog" checkbox
- The camera does not render the scene and the right eye is black.

**Screenshots**

![OpenXR-Controller-Sample-Edit-Mode](https://user-images.githubusercontent.com/28485330/114044572-3f961100-987f-11eb-8871-22afd30adcb7.JPG)
![OpenXR-Controller-Sample-Play-Mode](https://user-images.githubusercontent.com/28485330/114044578-415fd480-987f-11eb-9736-538a89b2eca7.JPG)

**Unity details:**

 - Flat Kit version: [2.1.6]
 - Unity version: [2020.3.3f1]
 - Graphics Pipeline: [URP]
 - URP version (if applicable): [10.4.0]
 - Development OS: [Windows]

**Additional context**

This bug was initially sent by email and acknowledged on 25/03/2021 - I'm adding it here for reference

**Comment by albrrt** [comment]
I figured out this issue happened because my OpenXR Render Mode was set to "Single Pass Instanced".

Setting your Render Mode to "Multi Pass" seems to fix it.

I didn't find any mention of this in the FlatKit documentation. According to Unity's documentation, Single Pass Instanced reduces CPU and GPU load, which makes this particularly desireable when developing lightweight games for untethered VR headsets.

Is there a plan to support Single Pass Instanced rendering in the future?

Thank you

**Comment by dustyroom-studio** [comment]
Thank you for the detailed steps.

While we work on single-pass support, I'm going to add the multi-pass workaround to the FAQ.

Related Issue: https://github.com/Dustyroom/flat-kit-doc/issues/23
