### ISSUE TITLE
URP Package giving errors. 

### ISSUE THREAD

**Issue by ShahNauman** [Dustyroom/flat-kit-doc#36]
Can't get the URP package to work with the new URP. 

**Shader error in 'FlatKit/Stylized Surface': redefinition of 'SurfaceData' at 2.0/Library/PackageCache/com.unity.render-pipelines.universal@10.4.0/ShaderLibrary/SurfaceData.hlsl(5) (on d3d11)**

Compiling Fragment program with _TEXTUREBLENDINGMODE_MULTIPLY
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_DESKTOP UNITY_LIGHTMAP_DLDR_ENCODING
Disabled keywords: _NORMALMAP _ALPHATEST_ON _ALPHAPREMULTIPLY_ON _EMISSION _METALLICSPECGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _OCCLUSIONMAP _SPECULARHIGHLIGHTS_OFF _GLOSSYREFLECTIONS_OFF _SPECULAR_SETUP _RECEIVE_SHADOWS_OFF _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHT_SHADOWS _SHADOWS_SOFT _MIXED_LIGHTING_SUBTRACTIVE DIRLIGHTMAP_COMBINED LIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON _CELPRIMARYMODE_SINGLE _CELPRIMARYMODE_STEPS _CELPRIMARYMODE_CURVE DR_CEL_EXTRA_ON DR_GRADIENT_ON DR_SPECULAR_ON DR_RIM_ON DR_VERTEX_COLORS_ON _UNITYSHADOWMODE_MULTIPLY _UNITYSHADOWMODE_COLOR _TEXTUREBLENDINGMODE_ADD UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_RGBM_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

Compiling Fragment program with _TEXTUREBLENDINGMODE_MULTIPLY
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_DESKTOP UNITY_LIGHTMAP_DLDR_ENCODING
Disabled keywords: _NORMALMAP _ALPHATEST_ON _ALPHAPREMULTIPLY_ON _EMISSION _METALLICSPECGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _OCCLUSIONMAP _SPECULARHIGHLIGHTS_OFF _GLOSSYREFLECTIONS_OFF _SPECULAR_SETUP _RECEIVE_SHADOWS_OFF _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHT_SHADOWS _SHADOWS_SOFT _MIXED_LIGHTING_SUBTRACTIVE DIRLIGHTMAP_COMBINED LIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON _CELPRIMARYMODE_SINGLE _CELPRIMARYMODE_STEPS _CELPRIMARYMODE_CURVE DR_CEL_EXTRA_ON DR_GRADIENT_ON DR_SPECULAR_ON DR_RIM_ON DR_VERTEX_COLORS_ON _UNITYSHADOWMODE_MULTIPLY _UNITYSHADOWMODE_COLOR _TEXTUREBLENDINGMODE_ADD UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_RGBM_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

**Shader error in 'FlatKit/Stylized Surface': redefinition of 'SurfaceData' at 2.0/Library/PackageCache/com.unity.render-pipelines.universal@10.4.0/ShaderLibrary/SurfaceData.hlsl(5) (on d3d11)**

Compiling Fragment program with _TEXTUREBLENDINGMODE_MULTIPLY
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_DESKTOP UNITY_LIGHTMAP_DLDR_ENCODING
Disabled keywords: _NORMALMAP _ALPHATEST_ON _ALPHAPREMULTIPLY_ON _EMISSION _METALLICSPECGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _OCCLUSIONMAP _SPECULARHIGHLIGHTS_OFF _GLOSSYREFLECTIONS_OFF _SPECULAR_SETUP _RECEIVE_SHADOWS_OFF _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHT_SHADOWS _SHADOWS_SOFT _MIXED_LIGHTING_SUBTRACTIVE DIRLIGHTMAP_COMBINED LIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON _CELPRIMARYMODE_SINGLE _CELPRIMARYMODE_STEPS _CELPRIMARYMODE_CURVE DR_CEL_EXTRA_ON DR_GRADIENT_ON DR_SPECULAR_ON DR_RIM_ON DR_VERTEX_COLORS_ON _UNITYSHADOWMODE_MULTIPLY _UNITYSHADOWMODE_COLOR _TEXTUREBLENDINGMODE_ADD UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_RGBM_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

**Comment by dustyroom-studio** [comment]
Hi,

Could you please share your Unity version and Flat Kit version with actual numbers? The Flat Kit's version can be found in a Readme file in Assets -> Flat Kit. 
Also, could you please let me know when does this issue happen?

Thanks

**Comment by ShahNauman** [comment]
Unity 2020.3.3f1 and Flat Kit is 2.1.6.

**Comment by dustyroom-studio** [comment]
This is an error when using an old version of Flat Kit with a newer version of Universal RP.

Could you please send me the screenshot of Flat Kit's Readme file as well as Flat Kit being selected in Package Manager (can be found in Window -> Package Manager -> My Assets)?

Also, could you please do the following:
- delete Flat Kit from the project, 
- exit Unity, 
- clean the cache of Package Manager, 
- re-open Unity 2020.3.3f1,
- go to Package Manager and download and import Flat Kit

The cache can be found here:
_Mac OS (hit Shift+Cmd+G in any Finder window and enter the following path):_ ~/Library/Unity/Asset Store-5.x
_Windows:_ C:\Users\accountName\AppData\Roaming\Unity\Asset Store-5.x

Please, watch the video about downloading and installing Flat Kit — found in the [chapter here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit).

**Comment by ShahNauman** [comment]
Worked! Thankyou!
