### ISSUE TITLE
'Stylized Surface With Outline' doesn't have transparency

### ISSUE THREAD

**Issue by ShahNauman** [Dustyroom/flat-kit-doc#37]
Changing the alpha value of the Color does not change the transparency even though the Surface Type is set to Transparent (Blend Mode = Alpha). Is there a way to add transparency to the shader?

**Comment by dustyroom-studio** [comment]
Thanks for reporting, we are able to reproduce this issue.
We'll submit a fix in an update to the Asset Store this week.
