### ISSUE TITLE
Screen Space Ambient Occlusion Render Feature not working with Flat Kit 

### ISSUE THREAD

**Issue by gillen033** [Dustyroom/flat-kit-doc#39]
**Describe the bug**
Models using Flat Kit shaders are not having ambient occlusion applied to them.

**To Reproduce**
1. Add the Screen Space Ambient Occlusion render feature to the Forward Render Data asset you are using. Add a model and assign a material that uses Flat Kit shader. The model does not have ambient occlusion.

**Expected behavior**
The model has ambient occlusion applied.

**Unity details:**
 - Flat Kit version: 2.1.5
 - Unity version: 2020.2.3f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 10.2.2
 - Development OS: Windows

**Build platform:**
 - Platform: Windows, however the issue is in editor

**Additional context**
I have tried to add the Flat Kit Depth Normals Render Feature before the SPAO, but it doesn't effect anything. I have also confirmed the models are not at fault by changing the material shader to URP->Lit, and SPAO worked after doing so. I'm probably missing something obviously and this is not a bug, however there are no other support options that I can find (why not start a Unity forum thread for Flat Kit??!!)

**Comment by dustyroom-studio** [comment]
Hello, thanks for reporting this.

We're aware of this issue and it has been fixed in Flat Kit 2.1.7. Please update your project to the latest version of Flat Kit.

**Comment by gillen033** [comment]
Okay, great. Is there any way to get around the bugged Package Manager and receive a direct download to the updated package? My invoice number is IN010001187325

 

I am using Unity 2020.2.3f1

**Comment by dustyroom-studio** [comment]
Hi,

Unity 2020.2.3f1 is the version where the issue had been fixed. You should be able to see the little Update button next to Flat Kit title in the Package Manager. If you don't see it, could you please send the screenshot of the Package Manager with Flat Kit being selected?

If for some reason it is not possible for you to update, please, give me your email address, I'll send the package to you. Please, note that it is not a preferred way to resolve this issue as you'll need to update to the following Flat Kit versions in the future.

**Comment by gillen033** [comment]
I tried updating it, but it stayed at 2.1.5. I cleared the Asset Store package manager cache, and when I did it showed 2.1.8 as the latest version to download. I downloaded it and tried to import but it said there was nothing new to import. I restarted Unity and went back to the Package Manager, and it now shows the package at 2.1.5, so clearly it did not download the latest version.

 

I know the Package Manager is supposed to be fixed in Unity 2020.2.3f1, but clearly that is not the case unfortunately.

 

My email is ***@***.***

 

I don’t understand the problem with getting the package this way? I should be able to update the package via the Package Manager in the future (once they have it fixed), right? Or are you saying that is not possible?

**Comment by dustyroom-studio** [comment]
For some reason I can't see your email in the comment above. Could you please send me a message to info@dustyroom.com?

Do you see the Update icon or triangle icon (versions drop down menu) in the Package Manager here:

![Screen Shot 2021-04-25 at 12 43 29 AM](https://user-images.githubusercontent.com/74666746/115973651-5ca93000-a55f-11eb-9e57-f17166435194.png)

or Update button here:

![Screen Shot 2021-04-25 at 12 34 51 AM](https://user-images.githubusercontent.com/74666746/115973598-f3c1b800-a55e-11eb-8040-9a8ace5c52c8.png)

If you don't see it, could you please send me the screenshot of your Package Manager with Flat Kit selected? Otherwise, just send me the mail and I'll provide you with the package.

**Comment by gillen033** [comment]
Hi, I sent you the email with my address.As for the Package Manager, the issue not that I can't see the update. If I clear my cache, it shows 2.1.18 (sorry if those numbers are slightly wrong, I am not on my computer to confirm) being available to download. I download it and the package Manager shows that I downloaded 2.1.18. However, if I hit import it says there is nothing to import, and if I close the package Manager and reopen it, it shows Flat Kit at 2.1.15 still.In addition, if I do not clear the cache, it shows the 2.1.18 package available as an update, however when I press the Update button (and after the progress bae fills), the same thing happens. It shows the update being successful (the version of the package changes), but importing does not work and restarting the package Manager shows the update as 2.1.15 still.So for some reason, it only wants to download 2.1.15, even though it is showing 2.1.18 as the most recent version available. I posted a few screen shots in this thread for reference:https://forum.unity.com/threads/package-manager-shows-latest-version-but-package-contents-is-not.1054007/#post-7073686On Apr 24, 2021 4:46 PM, dustyroom-studio ***@***.***> wrote:
For some reason I can't see your email in the comment above. Could you please send me a message to ***@***.***?
Do you see the Update icon or triangle icon (versions drop down menu) in the Package Manager here:

or Update button here:

If you don't see it, could you please send me the screenshot of your Package Manager with Flat Kit selected? Otherwise, just send me the mail and I'll provide you with the package.

**Comment by dustyroom-studio** [comment]
Hopefully with Flat Kit 2.2.0 it's easier to check for the latest version. Please re-open this bug if the issue persists.
