### ISSUE TITLE
flatkit bug issue

### ISSUE THREAD

**Issue by blackkkidkit** [Dustyroom/flat-kit-doc#41]
Hi, flatkit developer

**Describe the bug**
After I am import the URP Assets, it can't find a scriptable RP. I already deleted the temp file install again still have a same problem.

**To Reproduce**
1. Go to 'Package Manager' > Update > Import
2. Click on '[Render Pipeline] Universal (URP)' > all >installed. 
3. Scroll down to 'Fog\FlatKitFog.cs():error'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/82078165/116510570-b3b05b80-a8f7-11eb-86eb-ee0a6666bd2f.png)

**Unity details:**
Flat Kit: 2.1.5, URP: 10.4.0, Unity: 2020.3.0f1
 - Graphics Pipeline: [Bult-in or URP]
 - URP version (if applicable): [e.g. 10.3.1]
 - Development OS: [e.g. Windows]

**Build platform:**
 - Platform: [e.g. iOS]
 - Test device: [e.g. iPhone6]

**Additional context**

**Comment by blackkkidkit** [comment]
After I delete the FlatKit > [Render Pipeline]URP > RenderFeatures : fog file come up with a this error.
![image](https://user-images.githubusercontent.com/82078165/116512187-363a1a80-a8fa-11eb-9ba9-e8f49ea36997.png)

**Comment by dustyroom-studio** [comment]
Hi,

First of all,  please, make sure you import Flat Kit of the same rendering pipeline as it is in your Unity Project. During the import of Flat Kit you will need to choose one of the Unitypackages to extract the files from (I guess, it is the step 2 in your message.

If you work in URP, please, have a look at the video and written steps below the video 
(https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)

There you will see the how to import and install Flat Kit for URP.

If you can't follow the steps in the guide, please record a video or add the screenshots showing what prevents you from following it.

**Comment by blackkkidkit** [comment]
I am a 3d artist not very famous using Unity.

Sorry about that is not a bug for you develop, the problem come up bc I haven't install a URP package by Unity. That why can't detect the [FlatKit] URP.

If some one have the same problem, it may follow this link will be help to solve it. Cheers!
https://www.youtube.com/watch?v=m6YqTrwjpP0

**Comment by dustyroom-studio** [comment]
Thank you for letting me (and anyone interested) know, it can be a helpful bit of info!
Cheers.
