### ISSUE TITLE
Queue Offset (Priority in URP term)

### ISSUE THREAD

**Issue by yeonghoey** [Dustyroom/flat-kit-doc#42]
**Is your feature request related to a problem? Please describe.**

Can't control render orders in URP version. Apparently there's no option to tweak "Render Queue".

**Describe the solution you'd like**
Expose the Queue Offset (or Priorty in URP term) property to the material inspector.

**Describe alternatives you've considered**

I'm currently using a modified version of `StylizedSurfaceEditor.cs`, most of which are copied from `BaseShaderGUI.cs`

```c#
public class StylizedSurfaceEditor : ShaderGUI
{
    // ...
    // Field definition
    protected MaterialProperty queueOffsetProp { get; set; }5
    public readonly GUIContent queueSlider = new GUIContent("Priority",
        "Determines the chronological rendering order for a Material. High values are rendered first.");
    private const int queueOffsetRange = 50;

    // ...
    // Somewhere in OnGUI  
    queueOffsetProp = FindProperty("_QueueOffset", properties, false);
    DrawQueueOffsetField();

    // ...
    protected void DrawQueueOffsetField()
    {
        if (queueOffsetProp != null)
        {
            EditorGUI.BeginChangeCheck();
            EditorGUI.showMixedValue = queueOffsetProp.hasMixedValue;
            var queue = EditorGUILayout.IntSlider(queueSlider, (int)queueOffsetProp.floatValue, -queueOffsetRange, queueOffsetRange);
            if (EditorGUI.EndChangeCheck())
                queueOffsetProp.floatValue = queue;
            EditorGUI.showMixedValue = false;
        }
    }
```

**Additional context**
I think this kind of options are essential and hope it wolud be included in the future version.

**Comment by dustyroom-studio** [comment]
Hi,

Thank you very much for the detailed description of your request, it is really helpful. And thank you for a great suggestion.

We've added the feature you were asking for and will include it in the forthcoming update.

Thanks again.

**Comment by yeonghoey** [comment]
Cool, I'll look forward to it!
