### ISSUE TITLE
Shader error in Stylized Surface on fresh install

### ISSUE THREAD

**Issue by brentgmitchell** [Dustyroom/flat-kit-doc#46]
Just installed Flatkit URP and got a shader error, see attached photo.
![image](https://user-images.githubusercontent.com/6501377/118407573-a0381b00-b681-11eb-93cd-4a09ff9c407c.png)

**Unity details:**
 - Flat Kit version: 2.2.0
 - Unity version: 2020.2.2f1
 - Graphics Pipeline: URP
 - URP version (if applicable): ?
 - Development OS: Windows

**Comment by dustyroom-studio** [comment]
Hi, could you please try doing the following:
- Update to a more recent version of Unity. This will fix [the bug](https://issuetracker.unity3d.com/issues/package-manager-doesnt-show-available-updates) with the Package Manager.
- Check the version of Flat Kit. You told me it was 2.2.0 but the bug I mentioned above lies in the Package Manager not being able to download the latest versions of the assets, though it can display the latest version number. The only way to tell the version is to go Project tab -> Assets -> Flat Kit -> Readme, select it and you should see the version of Flat Kit, Unity, Universal RP. Making a screenshot would help. If you don't see the Readme file it means you've got too old version of Flat Kit. In this case you'll need to update it in the newer version of Unity first.
- Install as described in the video / text below the video - [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit).
