### ISSUE TITLE
VR Single Pass Instanced - Surface Outline 

### ISSUE THREAD

**Issue by TrueBeef** [Dustyroom/flat-kit-doc#5]
This may be less of an "_issue_" and more of an un-implemented feature, but when using VR with single-pass instanced mode, the outlines only render to one eye (left eye). I am currently looking for ways to modify this, though I am not experienced in shaderlab.

Issue is not found when using multi-pass mode for obvious reason, though my current target platforms require single-pass instanced mode for performance reasons.

Edit: Thought I'd add that the Issue still occurs when toggling each material to allow Instancing.

**Comment by TrueBeef** [comment]
So, I've modified the second pass block in the "Stylized Surface With Outline" shader with the below. This seems to fix the stereo rendering issue, though I'm wondering if there may be a more efficient way about it.

`
              
              struct VertexInput
             {
                float4 vertex : POSITION;
                float3 normal : NORMAL;

                UNITY_VERTEX_INPUT_INSTANCE_ID
             };

             struct VertexOutput
             {
                float4 vertex : SV_POSITION;
                float3 normal : NORMAL;

                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
             };

             VertexOutput VertexProgram(VertexInput v) {
                 VertexOutput o;

                 UNITY_SETUP_INSTANCE_ID(v);
                 UNITY_INITIALIZE_OUTPUT(VertexOutput, o);
                 UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);

                float4 clipPosition = UnityObjectToClipPos(v.vertex);
                float3 clipNormal = mul((float3x3) UNITY_MATRIX_VP, mul((float3x3) UNITY_MATRIX_M, v.normal));
                half outlineWidth = UNITY_ACCESS_INSTANCED_PROP(OutlineProps, _OutlineWidth);
                float2 offset = normalize(clipNormal.xy) / _ScreenParams.xy * outlineWidth * clipPosition.w * 2.0;
                clipPosition.xy += offset;
                half outlineDepthOffset = UNITY_ACCESS_INSTANCED_PROP(OutlineProps, _OutlineDepthOffset);
                clipPosition.z -= outlineDepthOffset;
                o.vertex = clipPosition;
                o.normal = clipNormal;
                return o;
            }

            half4 FragmentProgram(VertexOutput i) : SV_TARGET {
                
                UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(i);

                //UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(i);
                return UNITY_ACCESS_INSTANCED_PROP(OutlineProps, _OutlineColor);
            }
            `

**Comment by dustyroom-studio** [comment]
Thank you for looking into it! Your solution works and is efficient.
We've added fog back and will include it in the next update, probably this week.
Thanks again for finding a solution!
