### ISSUE TITLE
Stylised Surface Shader not reading in curve texture when opening Unity

### ISSUE THREAD

**Issue by henbull** [Dustyroom/flat-kit-doc#50]
**Describe the bug**
When using the stylised surface shader, with the curve option enabled, each time I open Unity, there's artifacts on the shader until I re-save the curve texture. 

**To Reproduce**
1. Save a Curve ramp texture on a stylised surface shader.
2. Close Unity
3. Re-Open unity and see artifacts
4. Re-save curve textur to remove artifacts

**Expected behavior**
I expectd that I wouldn't have to re-save the curve texture each time I open Unity. I wouldn't be able to use the curve option on many objects as it stands.

**Screenshots**
Aritfact: https://drive.google.com/file/d/14sJo0VrlkGxs4X9QD1HSxgLt6coK26jg/view?usp=sharing
No Artifact: https://drive.google.com/file/d/1tsvHCVjT2Mn_-3niouzHEUmfw1760MRt/view?usp=sharing

**Unity details:**
 - Flat Kit version: 2.1.8
 - Unity version: 2020.3.4f1
 - Graphics Pipeline: URP
 - Development OS: Both Mac and PC

**Build platform:**
 - Platform: IOS
 - Test device: [e.g. iPhone6]

**Comment by dustyroom-studio** [comment]
Hi,

Thank you for the detailed guide, I have just managed to replicate your issue.
We'll look into fixing it soon, meanwhile there is a possible temporary fix you can try.
- Locate the saved texture in the Project panel and select it;
- Look at the Inspector panel and find a _Wrap mode_ parameter
- Change the _Wrap mode_ to _Clamp_. Here's a screenshot:  

![stylized-surface-curve-mode-clamp-texture](https://user-images.githubusercontent.com/74666746/120456572-6879e480-c39e-11eb-9800-fdd9d174e55f.png)

Please let me know if it didn't work as a temporary workaround for you.

**Comment by henbull** [comment]
Hello,

Yep, the workaround is working.

Thank you!
