### ISSUE TITLE
Fog in Render Feature change all the view on camera to black

### ISSUE THREAD

**Issue by pandailing** [Dustyroom/flat-kit-doc#52]
**Describe the bug**
i want to use the Fog feature on my project, but when i activate it on my render feature, it goes all black

**To Reproduce**
1. Go to 'Project -> URP-> Settings ->ForwardRenderer'
2. Click on 'Add Renderer Feature' then add 'Flat Kit Fog', choose any fog settings
3. Activate the Flat Kit Fog on the Renderer
4. The View Screen become All Black

**Expected behavior**
the fog works and give the output as the settings told to

**Screenshots**
![image](https://user-images.githubusercontent.com/30192981/122678829-8d7dac80-d212-11eb-90ed-08aefd103055.png)
![image](https://user-images.githubusercontent.com/30192981/122678840-a1c1a980-d212-11eb-9fdd-cb5766cab9ef.png)

**Unity details:**
 - Flat Kit version: [2.2.5]
 - Unity version: [e.g. 2020.3.12f1]
 - Graphics Pipeline: [URP]
 - URP version (if applicable): 10.5.0
 - Development OS: [Windows]

**Additional context**
i had upgrade the project from unity 2019 to unity 2020 since it already LTS. but after fixing some material error, the fog make the screen black

**Comment by dustyroom-studio** [comment]
There's an update to the Flat Kit fog effect currently being reviewed by Unity (Flat Kit 2.2.6), I believe it should fix the issue you're seeing.

The update should appear in the Asset Store early next week. Please let us know if this problem persists after the update.
