### ISSUE TITLE
Water shader loses reflections when rendered on an overlay camera

### ISSUE THREAD

**Issue by antipirina** [Dustyroom/flat-kit-doc#53]
**Describe the bug**
I'm using a base camera for skybox and an overlay camera for the main elements. Water shader loses reflections when rendered on the overlay camera.

**Screenshots**
[Screenshot](https://i.imgur.com/Ay90JDN.png)

**Unity details:**
 - Flat Kit version: 2.2.6
 - Unity version: 2020.3.2f1
 - Graphics Pipeline: URP
 - URP version: 10.4.0
 - Development OS: Windows

**Comment by dustyroom-studio** [comment]
Hi,
Could you please share a few screenshots of your base / overlay cameras set-up? It would help me in trying re-creating the issue.
Thank you.

**Comment by antipirina** [comment]
Hi, thanks for answering.
[overlay cam](https://imgur.com/V9qadbm)
[base cam](https://imgur.com/a/jGWcrpG)
I'm using the Ocean Islands demo as a base scene.

**Comment by dustyroom-studio** [comment]
Unfortunately this is a limitation of the camera stacking in URP. The core problem is that the overlay camera can only use the depth texture of the base camera and does not render its own.

Flat Kit water shader uses the depth texture to render underwater objects and surface reflections. When water is rendered with an overlay camera, the depth texture is still coming from the base camera. However, in your set up the base camera does not render any opaque objects, only the skybox. As a result, the water shader does not have the information about depth.

Here's the relevant part from the [URP docs](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@10.4/manual/cameras-advanced.html):
```
At the start of its render loop, an Overlay Camera receives a depth buffer containing depth data 
from the previous Cameras in the Camera Stack.
```

To solve this you will need to make the depth camera render the opaque objects. Is it possible to swap layer masks of the base and overlay cameras?

**Comment by antipirina** [comment]
Thanks for your answer.
I can't change it cause my skybox is a bunch of models and a rotating sphere that follows the gameplay camera when panning, but doesn't move. I got that solution from an Unity demo. Even though looks like it doesn't work on URP. Thanks anyway, I'll change my approach.
