### ISSUE TITLE
StylizedSurface Error :  Couldn't open include file 'DustyroomStylizedLighting.cginc'

### ISSUE THREAD

**Issue by Roderick911** [Dustyroom/flat-kit-doc#54]
**Describe the bug**
Three of the shaders have an error.  They are StylizedSurface, StylizedSurfaceCutout, StylizedSurfaceOutline.  The StylizedSurfaceOutline renders pink while running, but fine in editor.  StylizedSurface renders perfectly despite the error. 

Here is the error.

Couldn't open include file 'DustyroomStylizedLighting.cginc'.
Compiling Fragment program with DIRECTIONAL _TEXTUREBLENDINGMODE_MULTIPLY
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR UNITY_PASS_FORWARDADD
Disabled keywords: FOG_LINEAR FOG_EXP FOG_EXP2 _CELPRIMARYMODE_SINGLE _CELPRIMARYMODE_STEPS _CELPRIMARYMODE_CURVE DR_CEL_EXTRA_ON DR_GRADIENT_ON DR_SPECULAR_ON DR_RIM_ON DR_VERTEX_COLORS_ON _UNITYSHADOWMODE_MULTIPLY _UNITYSHADOWMODE_COLOR _TEXTUREBLENDINGMODE_ADD POINT SPOT SHADOWS_SHADOWMASK LIGHTMAP_SHADOW_MIXING SHADOWS_DEPTH SHADOWS_SOFT SHADOWS_SCREEN SHADOWS_CUBE UNITY_NO_DXT5nm UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

**Unity details:**
 - Flat Kit version: e.g. 2.3
 - Unity version: 2020.3.3f1
 - Graphics Pipeline: Built-in 

 - Development OS:  Windows

**Comment by dustyroom-studio** [comment]
Hi, thanks for the included details. 
Unfortunately, we can't see any obvious reason for these errors. It really looks like something got imported not properly while you were installing Flat Kit. Could you please restart Unity, and if after that the issue persists, please navigate to Project panel -> Assets -> select 'Flat Kit' folder -> right click -> Reimport. 
Let us know if it is not fixed after you reopen Unity and reimport Flat Kit.

**Comment by Roderick911** [comment]
That fixed it!  Thanks so much!
