### ISSUE TITLE
Terrain shader layers support

### ISSUE THREAD

**Issue by itspers** [Dustyroom/flat-kit-doc#56]
**Describe the bug**

As i found out suddenly by looking at source Flatkit terrain shader supports only 4 layers. 😭

**Expected behavior**

-  would be good to have this at least in doc, or better straight on store page

**Question**

In general it looks fine, except **shadows** (Thats only reason i need it - i want sharp baked shadows with custom color). After layer 5 texture painted on shadowed place it not only dont draw shadow color, but also have 'native' dark color. So question is: can somebody point me ~line of code in shader, where i can tell it to paint custom shadow regardless of layer?

**Screenshots**
![flatkit](https://user-images.githubusercontent.com/833192/126405228-7cda574e-2f75-405d-b147-d89abbb3ef34.png)

**Unity details:**
 - Flat Kit version: 2.3.0
 - Unity version: 2020.2.3
 - Graphics Pipeline: URP
 - URP version (if applicable): 10.5
 - Development OS: Windows

**Comment by dustyroom-studio** [comment]
Hi, thank you for reporting this. We are unaware of this behavior and will try to replicate the issue following your steps. If it is a bug an we can reproduce it, we'll fix it as soon as possible.

Meanwhile, because I see you are using a very version of Unity, could you please locate the [Readme] debug helping file in Project panel -> Assets folder -> Flat Kit folder -> [Readme] file, select it, and send the screenshot of the Inspector panel?

Thank you.

**Comment by itspers** [comment]
Thank you! I was sure its because of 4 arrays everywhere in code, but if you say it is not expected behavior - will try to debug more.

Basically how to reproduce:

- create terrain with 5+ layers of textures
- put some object to cast shadow on it (works same with realtime and baked)
- pick Flatkits terrain shader and set some shadow color (red in my screenshots)
- paint layer 5 texture in shadowed place - it will ignore shadow settings and draw native shaded texture (even if you will completelly disable shadows in shader settings)


![image](https://user-images.githubusercontent.com/833192/126471926-57a072f9-1039-4e70-8f36-b1563f47c871.png)

**Comment by dustyroom-studio** [comment]
Thank you for letting me know your details and for the steps to reproduce this issue. It is a new one, we didn't have any reports about it before. Once I manage to recreate it, we'll try to fix this, hopefully for the following update.
Please, let me know if your project is on a tight deadline, in this case I'll offer you a refund. If you'd like it, please write to info@dustyroom.com.

**Comment by itspers** [comment]
thanks, i dont need refund and have time - for now will use default terrain

but in case terrain shader will need big refactoring - i would appreciate if you can share some temporary hack to make shadows work same regardless of layer!

**Comment by dustyroom-studio** [comment]
Thank you for your patience. I'll let you know as soon as we have any news.

**Comment by dustyroom-studio** [comment]
Hi, I'd like to let you know that we reproduced and have just fixed the issue. The Flat Kit Terrain shader now works with more than 4 layers as expected, hopefully without any shadow artifacts. Well submit the update shortly, it should be approved in a few days.
Thank you again for your patience.

**Comment by itspers** [comment]
Cool, thank you!
Will update once it will reach assets store and write feedback.
