### ISSUE TITLE
2020.2.2f1 import

### ISSUE THREAD

**Issue by at22f** [Dustyroom/flat-kit-doc#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
[](url)
![이미지 5](https://user-images.githubusercontent.com/93835851/140617936-99ef95d9-51e9-46b1-a161-fc5874eabddc.jpg)
![이미지 4](https://user-images.githubusercontent.com/93835851/140617943-ff6a4bdd-11c5-4b03-a438-0c38ffdb573a.jpg)
![이미지 3](https://user-images.githubusercontent.com/93835851/140617947-81a5d926-0159-4c36-97ef-d80ada2d4b81.jpg)

**Unity details:**
 - Flat Kit version: [e.g. 2.1.3]
 - Unity version: [e.g. 2020.2.3f1]
 - Graphics Pipeline: [Bult-in or URP]
 - URP version (if applicable): [e.g. 10.3.1]
 - Development OS: [e.g. Windows]

**Build platform:**
 - Platform: [e.g. iOS]
 - Test device: [e.g. iPhone6]

**Additional context**

**Comment by dustyroom-studio** [comment]
HI,
Flat Kit is compatible with the minimum Unity version of 2020.3.21. It is listed on the Asset Store Page. 

![Flat Kit Asset Store Compatibility Info](https://user-images.githubusercontent.com/74666746/140642465-6368f150-04ee-46de-bfe6-1a5f1fec57af.png)

Could you please update to the compatible version of Unity? If needed, please delete Flat Kit Folder and re-import it as shown in the [video here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)?

If the issue persists, please fill in those info bullet points from the template when you opened the issue ticket. We'll need to know the details to be able to help more.
