### ISSUE TITLE
Big gaps on outline with width > 1

### ISSUE THREAD

**Issue by FrankVisuals** [Dustyroom/flat-kit-doc#63]
**Describe the bug**

When using the Stylized Surface Shader with a width bigger than 1 I have big gaps between the outlines on my low poly model.

**To Reproduce**
1. Add Low Poly Model
2. Add Material if Stylized Surface Shader
3. Settings as image below

**Expected behavior**
I'd expect to have a clear outline, but it has gaps and looks bugged. Problem is even bigger on a higher distance

**Screenshots**

![image](https://user-images.githubusercontent.com/62556998/144842760-5d321888-60a8-4a2f-9b57-d2f9a9369992.png)
![image](https://user-images.githubusercontent.com/62556998/144842898-ce80429e-31f5-4bef-a178-4722d090aefd.png)
![image](https://user-images.githubusercontent.com/62556998/144842700-29b50bb9-829e-40d4-b32b-88efdd1ad398.png)

**Unity details:**
 - Flat Kit version: 2.6.5
 - Unity version: 2020.2.3f1
 - Graphics Pipeline: URP
 - Development OS: [e.g. Windows]

**Comment by dustyroom-studio** [comment]
Flat Kit has two ways of generating outlines: with the Stylized Surface shader and with the Outline Renderer Feature. The former is a quick one, and unlike Photoshop outline, it is a tool to work live with 3D objects, and It is best suited for the smooth rounded objects. The latter method gives precise outlines on the objects of any shape. 

When you use the Stylized Surface outline, in the URP version of Flat Kit you can see the **Scale** parameter. It is designed to make the outlines appear nicer on such sharp-angled meshes like the cubes. Please, look at the difference it makes to the outlines as opposed to using only the **Width** parameter.

![flat-kit-stylized-surface-outline-on-cube-scale](https://user-images.githubusercontent.com/74666746/144848319-61dc3b98-8e2f-4591-ada6-1eb7ee058b9f.png)

![flat-kit-stylized-surface-outline-on-cube-width](https://user-images.githubusercontent.com/74666746/144848708-2682503a-0950-4eb6-a2fe-fdd6171bdc33.png)

It is described in the documentation — [Stylized Surface, Main Parameters chapter](https://flatkit.dustyroom.com/#311-the-main-parameters-of-the-shader),
(please, scroll down to the 'Outline' paragraph).

This topic had been discussed earlier here in the Git Issues, for example [this one](https://github.com/Dustyroom/flat-kit-doc/issues/18).

**Comment by FrankVisuals** [comment]
thanks for the very fast support ! I missed that in the docs - sorry for that!
