### ISSUE TITLE
'CameraData.renderer' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by scruffduff** [Dustyroom/flat-kit-doc#66]
**Describe the bug**
When importing shader, using URP, the following errors occur:
1. "Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Fog\FlatKitFog.cs(37,67): error CS0122: 'CameraData.renderer' is inaccessible due to its protection level"
2. "Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Outline\FlatKitOutline.cs(41,67): error CS0122: 'CameraData.renderer' is inaccessible due to its protection level"

**To Reproduce**
1. New Project (2019.4.30f1)
2. Import URP, Import Shader from package manager
3. Install URP shader package from asset

**Expected behavior**
Successful shader import

**Unity details:**
 - Flat Kit version: 2.8.1
 - Unity version: 2019.4.30f1
 - Graphics Pipeline: URP
 - URP version: 7.7.1
 - Development OS: Windows 10

**Comment by dustyroom-studio** [comment]
Hi! This happens because Flat Kit requires at least Unity 2020 and URP 10.
If upgrading Unity is not an option, please email us to send you an older version of Flat Kit.

**Comment by scruffduff** [comment]
Hi,
Upgrading is not an option as I am using Uni PC which I do not have admin privileges on.  Please send over the older version. Which version is more stable for 2019.4.30f1 (built-in rendering or URP) & which would you recommend using on open-world projects?
All the best,
Joe
________________________________

**Comment by dustyroom-studio** [comment]
Hi, no problem at all. Please let us know your invoice number at
***@***.***

**Comment by dustyroom-studio** [comment]
Thank you! Please still email us for the package, we cannot share it here.
