### ISSUE TITLE
Render issues on Apple Silicon

### ISSUE THREAD

**Issue by OrionFive** [Dustyroom/flat-kit-doc#68]
**Describe the bug**
When running an executable (built for OSX from cloud, using Unity 2020.3.25f), the game does not render correctly (at all).

**To Reproduce**
1. Build OSX executable using Cloud build
2. Run on apple silicon computer
3. Enjoy lightshow

**Expected behavior**
The game renders correctly without artifacts.

**Screenshots**
<img width="1440" alt="Screen_Shot_2022-03-03_at_2 05 59_PM" src="https://user-images.githubusercontent.com/13980562/157104930-88ac0c4f-1096-4aee-9dc9-eb643696bca1.png">
<img width="1440" alt="Screen_Shot_2022-03-03_at_2 05 41_PM" src="https://user-images.githubusercontent.com/13980562/157104933-92674197-5d47-4fee-9bac-b13c8440658a.png">

**Unity details:**
 - Flat Kit version: [2.5.2]
 - Unity version: [2020.3.25f1]
 - Graphics Pipeline: [URP]
 - URP version (if applicable): [10.7.0]
 - Development OS: [Windows 10]

**Build platform:**
 - Platform: [OSX]
 - Test device: [Apple silicon]

**Additional context**
It renders correctly on other apple and windows devices.
I'm going to test the latest Flat Kit version soon. This was reported by a user, so I don't own the device it ran on.

**Comment by dustyroom-studio** [comment]
Hi, we'd like to reproduce this issue, in order to be able to debug it.
To help us do it efficiently, could you please share a guide how we could recreate the problem — either in one of the demo scenes, or in the fresh scene?
Thank you.

**Comment by dustyroom-studio** [comment]
Also, is the issue reproducible with Flat Kit 2.9.0?

**Comment by OrionFive** [comment]
Like I wrote, I don't own the device on which it breaks, so I can't test easily when it does.

I'll send a version with 2.9.0 to the user today. I suppose I can build and send a demo scene as well.

**Comment by OrionFive** [comment]
So I've had contact again with the user. The latest version of Flatkit causes the same issue on the device.I'll create a test version for one of the demo scenes next.

**Comment by OrionFive** [comment]
Okay, by now we've got a second user with the same issue. It's happening on a Macbook Air with an integrated M1 processor. On an M1 Max it does not occur.

**Comment by dustyroom-studio** [comment]
Hi @OrionFive 
I've just created a build for Apple silicon and tested on a Macbook with the M1 chip. The build worked fine.
Can you please test with a minimal scene to narrow down the problem? E.g. a build from a fresh Unity project with one cube rendered with Flat Kit.
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/74666746/158066391-3b29df60-82d3-424b-8171-1a58d782110f.png">

**Comment by OrionFive** [comment]
As I already wrote, if I build the ocean islands scene in a new project, it works fine.
So it must be a specific setting, or combination of settings, or combination of packages that breaks rendering.
So a simple scene won't give us any answers, unfortunately.
I'm now creating a series of builds, each more like our game, to see at which point it breaks for the user.

**Comment by dustyroom-studio** [comment]
I hope you found the root cause. If so, please let us know. Closing this issue shortly.

**Comment by OrionFive** [comment]
That is fine. Unfortunately, I haven't managed to find the cause yet. I've given up temporarily, though, since it had become too much of a time sink.
Should I obtain any new information, I'll reopen the case.
