### ISSUE TITLE
Flatkit compilation error 

### ISSUE THREAD

**Issue by JMFrancia** [Dustyroom/flat-kit-doc#7]
Unfortunately I seem to be hitting a compilation error on several of the included shaders in the packages. I followed the precise steps outlined in your manual. I’m using Unity 2020.2.0f1, Universal RP version 10.2.2, and my build target is IOS. This compilation error shows up as soon as I try and apply one of your shaders to any material: 

> Shader error in 'FlatKit/Stylized Surface': 'InitializeInputData': output parameter 'inputData' not completely initialized at Assets/FlatKit/Shaders/StylizedSurface/LibraryUrp/LitForwardPass_DR.hlsl(55) (on metal)
> 
> Compiling Fragment program with _TEXTUREBLENDINGMODE_MULTIPLY
> Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHTMAP_DLDR_ENCODING
> Disabled keywords: UNITY_2020_2_OR_NEWER _NORMALMAP _ALPHATEST_ON _ALPHAPREMULTIPLY_ON _EMISSION _METALLICSPECGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _OCCLUSIONMAP _SPECULARHIGHLIGHTS_OFF _GLOSSYREFLECTIONS_OFF _SPECULAR_SETUP _RECEIVE_SHADOWS_OFF _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS _ADDITIONAL_LIGHT_SHADOWS _SHADOWS_SOFT _MIXED_LIGHTING_SUBTRACTIVE DIRLIGHTMAP_COMBINED LIGHTMAP_ON FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON _CELPRIMARYMODE_SINGLE _CELPRIMARYMODE_STEPS _CELPRIMARYMODE_CURVE DR_CEL_EXTRA_ON DR_GRADIENT_ON DR_SPECULAR_ON DR_RIM_ON DR_VERTEX_COLORS_ON _UNITYSHADOWMODE_MULTIPLY _UNITYSHADOWMODE_COLOR _TEXTUREBLENDINGMODE_ADD UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_RGBM_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

I’ve looked online for solutions, and tried applying the unity preprocessor macro UNITY_INITIALIZE_OUTPUT(Input, o) but for whatever reason Unity doesn’t appear to be recognizing it; it’s coming up as undefined.

**Comment by dustyroom-studio** [comment]
Hi,

This issue should be fixed in the next Flat Kit update, which is currently in review by Unity.

Have you tried the [workaround from our FAQ](https://github.com/Dustyroom/flat-kit-doc/blob/master/index.md#q-flat-kit-does-not-work-in-unity-20202)?

**Comment by JMFrancia** [comment]
I will try that. Sorry I did not notice it in the FAQ. Thank you for the quick response!
