### ISSUE TITLE
Error when trying to unpack Built-in RP

### ISSUE THREAD

**Issue by junkeh89** [Dustyroom/flat-kit-doc#74]
**Describe the bug**
After importing the asset I am unable to unpack Flat Kit for Built-in RP from the Readme file, as the unpacking fails and instead I get 2 error messages in the console(please see attached screenshots). Double clicking the package file in the Flat Kit folder produces the same result.

I have tried redownloading the asset, but nothing changes. I have also tried unpacking the URP package and it worked as expected.

**To Reproduce**
1. Import the asset
2. Click on the Readme file in the Flat Kit folder
3. Click on Built-in RP

**Expected behavior**
I expected to be able to unpack and install Flat Kit for Built-in RP.

**Screenshots**
<img width="1018" alt="Screenshot 2022-04-22 at 15 04 39" src="https://user-images.githubusercontent.com/67078796/164735676-c99c26a4-7425-47e2-a279-c0c6bd695e0c.png">
<img width="1019" alt="Screenshot 2022-04-22 at 15 04 59" src="https://user-images.githubusercontent.com/67078796/164735690-965cc6ca-11e7-437e-aca5-6232f16b1796.png">

**Unity details:**
 - Flat Kit version: 2.9.8
 - Unity version: 2021.2.19f1
 - Graphics Pipeline: Built-in
 - URP version (if applicable): n/a
 - Development OS: MacOS Ver. 10.14.6 Mojave 

**Build platform:**
 - Target Platform: Windows/Mac
 - Test device: Macbook Pro 2018, low-end Windows10 PC

**Additional context**
n/a

**Comment by dustyroom-studio** [comment]
Hi, thank you for your detailed report.
I have just tried to import Flat Kit Built-In RP into a fresh project — it went without any issue.

When trying to re-import, have you tried cleaning the cache before the import? Since your import went with issues, you probably don't have the [Readme] file installed (Assets/Flat Kit) — you can clear the cache using this tool. 

![flat-kit-remove-cache-readme](https://user-images.githubusercontent.com/74666746/164749475-0bc12c8f-c869-4d15-b1da-95303586d8f4.png)

If the [Readme] tool is indeed broken, please, try cleaning the cache manually:
- open a Finder window in macOS 
- hit Cmd + Shift + G and paste this path: 
~/Library/Unity/Asset Store-5.x
- delete the folder Dustyroom
  <img width="417" alt="flat-kit-remove-cache-finder-window" src="https://user-images.githubusercontent.com/74666746/164747743-6c981ddc-a3b3-4621-9f83-3c2a1d97d191.png">
- restart Unity
- go to Package Manager, locate Flat Kit and try re-importing

Also, do you have an opportunity to check if this happens in any other versions of Unity?

One more (probably stupid) question is if you have enough space on your drive.

Alternatively, if after clearing the cache and re-importing and trying in other Unity versions the issue reoccurs, please let me know, I can send you the unitypackage to your mail to test if you can unzip it this way.

**Comment by junkeh89** [comment]
Hi and thanks for the quick reply.

I went and manually cleaned the cache, then reopened my project in Unity, downloaded the asset from the Package Manager, imported it into my project and I get the same 2 errors as before.

I also tried importing and unpacking in a fresh project without any other assets imported and I get the same result.

Finally, I tried importing and unpacking in a new project in Unity 2020.3.33f1, but I still get the same result.

It doesn't look like I'm missing any files, although my Readme file looks slightly different in the Inspector than the one from your screenshot. I'm attaching a screenshot of what my Unity window looks like, in case it helps in any way. Thanks!

<img width="1676" alt="Screenshot 2022-04-22 at 18 17 09" src="https://user-images.githubusercontent.com/67078796/164763443-61e99257-b66b-40da-9a3e-999494d7e18f.png">

**Comment by junkeh89** [comment]
Sorry, forgot to mention, there is enough free space on my drive, so that shouldn't be the issue. Cheers!

**Comment by dustyroom-studio** [comment]
The [Readme] tool has a different look for pre-unzipped and unzipped Flat Kit unitypackage — the [Readme] on your screenshot is telling that you haven't yet unpacked Flat Kit. So, just to confirm, once you try pressing the 'Unpack Flat Kit for Built-In RP' button (displayed on your screenshot), it gives the errors, correct? We're looking closer into it.

**Comment by junkeh89** [comment]
That is correct. As soon as I press "Unpack Flat Kit for Built-In RP" I get the 2 errors.

**Comment by dustyroom-studio** [comment]
Can you please re-download the asset in the Package Manager? The only reason I can see for this error is the asset being somehow incompletely downloaded.
Please delete the `FlatKit` folder from your project, use the "Re-Download" button and then re-import the asset and unpack the Built-In Package using the Readme again.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/74666746/164772174-4cd7a3b4-d0e6-4c49-a956-d4157ee725c5.png">

**Comment by junkeh89** [comment]
Sadly, this doesn't work either. It's actually one of the first things I tried, before deciding to post here, and I tried it again now and I'm still getting the same 2 error messages.

**Comment by dustyroom-studio** [comment]
That's very strange, we haven't seen that problem yet.
Can you please try the solutions in [these instructions from Unity](https://support.unity.com/hc/en-us/articles/360039196172-I-am-getting-errors-in-the-console-when-importing-an-Asset)? 
Also, does the URP package get unpacked successfully?

**Comment by dustyroom-studio** [comment]
I've just looked through the reported issues in the past and found exactly the same one. In that case they fixed it by re-downloading, it is indeed strange that it didn't help you.
What size is your downloaded unitypackage?

<img width="381" alt="flat-kit-unitypackage-size" src="https://user-images.githubusercontent.com/74666746/164780378-b8e104bf-960f-4a53-8c2d-d0cf26dd6821.png">

**Comment by junkeh89** [comment]
I've tried deleting everything and downloading the asset again, but I still can't unpack it.

My downloaded unitypackage is the same size as the one in your screenshot, 58.1mb.

<img width="266" alt="Screenshot 2022-04-22 at 21 07 13" src="https://user-images.githubusercontent.com/67078796/164786666-ccaf9ab8-8b8a-4eba-aa0b-5c2fb86a0ed6.png">

**Comment by dustyroom-studio** [comment]
The only other suggestions I can think of is trying a fresh project and another version of Unity.
One thing I'm sure is that this is not related to the asset itself, but to Unity or the OS.

**Comment by junkeh89** [comment]
I've tried it on 2021.2.19f1, 2020.3.33f1 and 2019.3.15f1, all with the same results. Is there an alternative way to download the asset or the Built-in RP package?

**Comment by dustyroom-studio** [comment]
Please, send me an email to info@dustyroom.com and I'll provide you with a direct download link to the very package that I tested and that worked for me.

**Comment by junkeh89** [comment]
On it now, cheers!
