### ISSUE TITLE
Pink textures help!

### ISSUE THREAD

**Issue by Skskskskskskssss** [Dustyroom/flat-kit-doc#75]
**Describe the bug**
pink and flashing graphics

I followed what you said here and the docs.
https://github.com/Dustyroom/flat-kit-doc/issues/22
**Expected behavior**

**Screenshots**
https://gyazo.com/4b1ea27a8dc812852460a72c8e0c34f5
https://gyazo.com/635ee0a460a9077cc5203b4084937f54

**Unity details:**
 - Flat Kit version: newest
 - Unity version: 2021.1.1
 - Graphics Pipeline: URP
 - URP version (if applicable): newest
 - Development OS: windows

**Build platform:**
 - Platform: [e.g. iOS] windows
 - Test device: [e.g. iPhone6] windows
 URP working fine before. once I added flatkit it blew up do you know whats going on? Do i have to change the shaders manually!?!

**Comment by dustyroom-studio** [comment]
Hi! Thanks for the details.

First of all, you do not need to change shaders. This is most likely some version mismatch.

Some questions to help us debug:
- Are you using the `[Flat Kit] Example Forward Renderer`? Can you please share a screenshot of the Renderer Asset you're using?
- Do the samples included with Flat Kit render OK?

**Comment by Skskskskskskssss** [comment]
Issue resolved it was on my end. I had a shader error from missing shaders from another asset. 
 I do have one question and I really appreciate your help.
how do I exclude something from being outlined? Its outlining my sky

**Comment by dustyroom-studio** [comment]
As you may know, Flat Kit has two methods of outlines: the [shader based using the Stylized Surface shader (per material)](https://flatkit.dustyroom.com/#31-stylized-surface-shader) and [scene based (per renderer feature)](https://flatkit.dustyroom.com/#42-outline-image-effect).

While the former can be used independently for each material, the latter needs to be applied as the image effect for the whole world space — it is how Unity works: the image effects are global.

There are ways to overcome this moment. For example, you can stack the cameras. Each one of the cameras has a separate forward renderer selected. Each of these forward renderers has its own Outline image effect, of course, with different settings. When stacked, these cameras result in multiple Outline image effects placed on top of each other. If you need one camera not to render the outlines at all, you can set outline width to 0 or bypass the Outline Renderer Feature, for example. It can be more taxing on the to the performance. Also, there are some limitations due the way URP operates.

Also, if you set any material to transparent, the Outline Image Effect can bypass transparency and not render the outline for that material. This won't affect the look but using the right Render Event parameter (please, look into [this chapter](https://flatkit.dustyroom.com/#42-outline-image-effect)), you can bypass the global outline on the scene on some materials.

Regarding the outlines skybox, you may, again, look into the Render Event parameter of the outline — [here](https://flatkit.dustyroom.com/#42-outline-image-effect). In this case, please, try setting it to the 'Before Rendering Transparents' mode, or any other that suits your project. Please, don't forget to press Play to see the effect.

**Comment by Skskskskskskssss** [comment]
Thank you!!!
