### ISSUE TITLE
Error on FlatKit install URP - Unity V 2021.3.5f1

### ISSUE THREAD

**Issue by Gohloum** [Dustyroom/flat-kit-doc#82]
I am attempting to use FlatKit URP with a new, clean project. However I have 34 errors, and when going to the project Settings, I can not add the [FlatKit] Example Setting URP asset to the rendering pipeline field.

To reproduce, start with a new project of Unity 2021.3.5f1
Follow the directions in the Manual PDF, choose to import URP all assets except buit in renderer from import window. 
Once imported, follow ReadMe direction and import the URP assets.
Upon import completion, 34 errors.
Go to Project Settings and attempt to set Example Settings URP under Graphics - will not work.

**Unity details:**
 - Flat Kit version: [e.g. 3.0.0]
 - Unity version: [e.g. 2021.3.5f1]
 - Graphics Pipeline: URP
 - Development OS: [e.g. Windows]

**Build platform:**
- Windows, Mac, Linux [Windows 64 bit]
- Web GL

*** NOTE - it looks like there is some sort of missing name space issue.  Not sure which one it is, but as you can see it's blocking compilation of core classes and the "no suitable method found to override" message.  See below: ***

** Console Errors ""
// a few of the errors pertaining to namespace 'Universal'
Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Common\BlitTexturePass.cs(3,29): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Fog\FlatKitFog.cs(3,29): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Outline\OutlineSettings.cs(2,29): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

// a few errors pertaining to 'ScriptableRendererFeature'
Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Fog\FlatKitFog.cs(10,27): error CS0246: The type or namespace name 'ScriptableRendererFeature' could not be found (are you missing a using directive or an assembly reference?)

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Outline\FlatKitOutline.cs(10,31): error CS0246: The type or namespace name 'ScriptableRendererFeature' could not be found (are you missing a using directive or an assembly reference?)

// ScriptableRenderPass...
Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Common\BlitTexturePass.cs(10,34): error CS0246: The type or namespace name 'ScriptableRenderPass' could not be found (are you missing a using directive or an assembly reference?)

// Other errors....
Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Common\BlitTexturePass.cs(33,63): error CS0246: The type or namespace name 'RenderingData' could not be found (are you missing a using directive or an assembly reference?)

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Outline\FlatKitOutline.cs(32,26): error CS0115: 'FlatKitOutline.Create()': no suitable method found to override

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Outline\FlatKitOutline.cs(66,29): error CS0115: 'FlatKitOutline.Dispose(bool)': no suitable method found to override

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Fog\FlatKitFog.cs(42,26): error CS0115: 'FlatKitFog.Create()': no suitable method found to override

Assets\FlatKit\[Render Pipeline] URP\RenderFeatures\Fog\FlatKitFog.cs(78,29): error CS0115: 'FlatKitFog.Dispose(bool)': no suitable method found to override

**Comment by Gohloum** [comment]
Ha! I got it.  In your documentation it says that the FlatKit is "Self Contained", therefore I did not think to import the Universal RP from the Package Manager under "Unity Registry".  

My oversight, but just to help others, you might want to add this as a step before importing the package if one is planning to use URP.

**Comment by dustyroom-studio** [comment]
Hi! Is the Universal Render Pipeline imported in the project (using Package Manager)?
