### ISSUE TITLE
URP renderer feature not showing in editor

### ISSUE THREAD

**Issue by Blacklotus45** [Dustyroom/flat-kit-doc#86]
**Describe the bug**
URP Renderer Feature's (Fog, Outline etc.) not showing in **live editor gameplay**

**To Reproduce**
1. Unity 2021.3.5f1
2. Clean import
3. Set renderer in both Quality and Graphics settings
4. Got to Wanderer scene or Fruit Vase 7 Outline Image effect
5. Watch *Game* tab the press play

**Expected behavior**
Rendering *Renderer features* in editor live gameplay.

**Screenshots**
![image](https://user-images.githubusercontent.com/22615437/182611426-2467efb5-4b03-4546-8f63-3dac61580bd1.png)
![image](https://user-images.githubusercontent.com/22615437/182611483-e0ee00f0-6212-4e69-afa6-41568bc2e66e.png)
![image](https://user-images.githubusercontent.com/22615437/182611561-3c32d93b-e967-4d1d-9ff6-10d940827700.png)
![image](https://user-images.githubusercontent.com/22615437/182611598-c70565f0-7a66-4d1e-960c-d93b7cae032d.png)

**Unity details:**
Flat Kit version 3.0.1
Unity 2021.3.5f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.7
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: [FlatKit] Example Settings URP
Graphics config: [FlatKit] Example Settings URP

**Build platform:**
 - Platform: Unity Editor (Win)
 - Test device: Amd 5900X & Amd 5600XT

**Additional context**
Disabling and re enabling while game runs fix the issue in live gameplay.
Tested with unity ssao renderer feature and it works while others don't. (Both at top and bottom of feature stack)
There is no problem with preview as in the Screenshots.
Windows build works as expected.

**Comment by dustyroom-studio** [comment]
Thanks for the detailed report! We can't reproduce the problem so far.
Please check this video - am I doing everything correctly to reproduce this?
https://drive.google.com/file/d/1w7X6A0AbRIYj9lLs4py25mm6XmqL9pU8/view?usp=sharing

**Comment by Blacklotus45** [comment]
Further digging gave result. It is bound to **Enter Play Mode Settings**, domain and scene reload stuff.
Domain has to be reloaded but scene can be reused from what I see.

**Comment by dustyroom-studio** [comment]
I wasn't aware of that, thanks for letting us know!
