### ISSUE TITLE
Flat Kit Fog render features stops working when changing quality settings (URP)

### ISSUE THREAD

**Issue by plebon** [Dustyroom/flat-kit-doc#87]
In URP, when changing quality settings at runtime, the Flat Kit Fog render features stops working. 

**Steps to reproduce the behavior:**
1. Open the Wanderer Demo scene in with Unity 2021.3.7f1 
2. Change the Render pipeline asset to use Flatkit example URP settings as per documentation
3. Create a Copy of the "[FlatKit] Example Settings URP" config and change a setting (i.e. Shadow Cascade count ->  3)
4. Set this new config as the medium/Balanced "Render Pipeline Asset"
5. Play the sample scene
6. Change the Quality Level from the Project Settings to Medium/Balanced
7. See that the Fog no longer works. It also does not work when switching back to High Quality.

**Expected behavior**
The Fog setting should work if the other quality setting also has the same render features.

**Unity details:**
Flat Kit version 3.0.1
Unity 2021.3.7f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.7
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: [FlatKit] Example Settings URP (Med)
Graphics config: [FlatKit] Example Settings URP (Med)

**Additional context**
I have verified the issue on a Development and Release Build in my main project. If I change the quality option in a gameplay scene while the fog is rendering it no longer works for the rest of the time in game. If I quit the game completely and come back it will work again. 

I can change the quality from the main menu (just UI without the fog render feature) and it will work when running the gameplay scene.

**Comment by dustyroom-studio** [comment]
This should be fixed in v. 3.0.5, which should appear on the Asset Store in a few hours.
Please re-open this ticked if the issue persists.
