### ISSUE TITLE
Shader Variant Compiling

### ISSUE THREAD

**Issue by psyconius** [Dustyroom/flat-kit-doc#89]
**Describe the bug**
It appears that when I go to compile, FlatKit makes Unity want to do a LOT of shader variants. 154618M.

**To Reproduce**
So I try to compile as usual. I only have 36 shaders with 79 total variants but I get the above listed variants:

![image](https://user-images.githubusercontent.com/63046565/195459847-8438d3f5-ae27-42a8-9d77-5cec14ececd3.png)

![image](https://user-images.githubusercontent.com/63046565/195459819-9da0a9cc-09dd-47b8-8675-0c1a552da038.png)

I removed ALL shaders from the Always Included Shaders list and my project compiled in 20 seconds but when run it of course was all pink. I went back and added JUST Stylized Surface and tried to build and it went right back to the 154 trillion shader variants.

**Expected behavior**
I expect it to only use proper shader variants. I've even tried using "Shader Control" from the asset store to disable certain keywords and it still wants the full 154 trillion.

**Screenshots**
see above.

**Unity details:**
 - Flat Kit version: 3.0.5
 - Unity version: 2021.3.10f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 12.1.7
 - Development OS: Windows

**Build platform:**
 - Platform: Windows
 - Test device: Ryzen 3700X/32GB RAM/RTX 3070

**Additional context**
I know nothing about shaders. I've googled these issues and apparently since about 2021.2 (URP 12) shader variants have gotten out of hand for people and require many many hours of compiling for some projects. However, this seems even outside of that scope. I would love to provide any sort of assistance to you that you would require in replicating. I will also continue to tinker with things on my end. Otherwise, please do reach out and I will be happy to help.

**Comment by dustyroom-studio** [comment]
Hi! We are not able to reproduce the issue so far, using the same URP and Unity major version compiling is relatively quick in our experiment. Can you please try building a demo scene included with the asset (e.g. "Pool" scene)? Does the issue persist?

**Comment by psyconius** [comment]
If I don't have Stylize Surface in the Shader list it compiles in seconds but everything is pink. If I have it in the list I am back to trillions:

![image](https://user-images.githubusercontent.com/63046565/195473003-fcc0a0ec-2f19-400b-a08c-54b695d4859d.png)

[ProjectSettings.zip](https://github.com/Dustyroom/flat-kit-doc/files/9769471/ProjectSettings.zip)

I am attaching my projectsettings folder to see if you see any weirdness. I am also I guess going to abandon this project ultimately and copy over my work to a fresh project start too? I have no clue what is happening.

**Comment by dustyroom-studio** [comment]
So you've tried building a demo scene and it still has lots of variants? In that case trying a fresh project is a good idea. But before transferring your work over to the new project, please try building a demo scene again to check if the issue is gone in that project.

**Comment by psyconius** [comment]
Yeah it looks like the new project compiling the pool takes seconds. 

I have no idea how my project got so bogged down. I want to say maybe Nature Render 2020 could be to blame. As far as I can tell, it intercepts ALL shader imports so it can add to them. I wonder if that did it.

I will start importing my work into this project and see how it goes. Otherwise, this clearly doesn't seem like a you guys thing. Thank you so much for your speedy responses.

**Comment by psyconius** [comment]
![image](https://user-images.githubusercontent.com/63046565/195509953-fb36116f-1c35-44a6-87ea-70d1abccfe81.png)

I didn't even see the M display. Took me 3:30 to compile the Polygon Nature scene with some added characters and Stylized Surface on some stuff. Looks to be resolved. Really wish I could figure out where it went wrong but looks like I am good. Thank you guys.
