### ISSUE TITLE
Flat Kit Outline Not Showing In Build But Present In Game View

### ISSUE THREAD

**Issue by Lunestro** [Dustyroom/flat-kit-doc#90]
Hello

First, I am an extremely new "developer".  I have next to know knowledge and have been teaching myself everything from coding to the use of Unity for the past few months during my free time.  With this said, I do not have an extensive knowledge of things by any degree, but I've learned a great deal from the community with the time I have put in.

The issue I am having is when I play my current build in the Game View, I can see the effect of the Flat Kit Outline as I intend to use it.

<img width="1053" alt="With Outline" src="https://user-images.githubusercontent.com/116459989/197358474-25a2fc2b-3b59-434b-aaee-aa41c2475ef1.png">

However, when I build and "Play" what I have so far, the effect of the outline is not present.

<img width="1773" alt="Without Outline" src="https://user-images.githubusercontent.com/116459989/197358626-a2330444-e0e0-494a-babb-c5329f1282e4.png">

You can see some outline there, but that's from the effect of the Quibli/Sylized Lit shader on the material (I much prefer it's cel shading ability to Flat Kits) - yes, I am using both Flat Kit and Quibli.

The renderer I am using is the Quibli Example Settings, but I did try the Flat Kit Example settings with no success.

**Comment by Lunestro** [comment]
Some images that may or may not be of use.

<img width="459" alt="Render Pipeline Asset" src="https://user-images.githubusercontent.com/116459989/197358865-4f64ff55-e243-4345-890c-2d740af27834.png">
<img width="465" alt="Universal Renderer Data" src="https://user-images.githubusercontent.com/116459989/197358873-516114b5-1758-4da2-b159-8ee167450772.png">
<img width="436" alt="Example Outline Settings" src="https://user-images.githubusercontent.com/116459989/197358880-1a189502-0c8f-442a-bf6a-89b90dfd9f36.png">

**Comment by dustyroom-studio** [comment]
You're right, this shouldn't happen, Game View should always be the same as the build. Thanks for the details.
Can you please copy the debug details from Flat Kit's Readme file?
Another quick question - does the same happen if you build one of the demos included with Flat Kit (e.g. Wanderer)?

**Comment by dustyroom-studio** [comment]
The logo looks great BTW.

**Comment by Lunestro** [comment]
Flat Kit version 3.0.6
Unity 2021.3.11f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.7
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: Quibli URP Config
Graphics config: Quibli URP Config

For what it's worth, as I mentioned before, I did try the Flat Kit for the Quality and Graphics config.  I can do so again and post that information if it's helpful to you.

I attempted a build with the Wanderer demo scene and the same things seems to be true - there is no outline.

I completely suspect this is something of my own doing and not a fault with Flat Kit or Quibli, I just have no idea what it may be after a great deal of searching.

Thank you for the compliment, by the way!  It has been a lonely journey so far so that little bit of feedback is most helpful!

**Comment by dustyroom-studio** [comment]
My guess is that the image effect shaders do not get included in the build for some reason. Can you please add these three shaders in "Always Included" (Project Settings -> Graphics)?
![image](https://user-images.githubusercontent.com/74666746/197367617-ddf0cdd0-042e-40c5-9f20-b547ae777567.png)

**Comment by Lunestro** [comment]
That absolutely fixed it.  Thank you very, VERY much!

As someone who is just beginning his journey into game development with nothing but a passion for creativity, I am completely impressed with your studio.  Thank you so much for taking the time to help me - especially since the issue doesn't seem to have come from your asset.  The fact that you helped me to get it working anyway is most impressive to me.

I also learned something!  I had no idea such a thing existed.  As someone starting, there's a lot of stuff I see and it's just foreign to me, so this helps to make the puzzle of what I am looking at sometime all that much more clear.  Your studio is a testament to the positive community I tell others about when I am cast judgements of uncertainty when I share my development endeavors and I will make sure to tell others about the help you've given me.

It may seem small to you, but for me it's a very big deal.

Thank you very much.  I will absolutely be looking for more to come from your studio in hopes that I will have a place for it in my own creative works.

Thank you again.

Stay safe!

Lunestro
