### ISSUE TITLE
Water shader has no waves

### ISSUE THREAD

**Issue by iv2b** [Dustyroom/flat-kit-doc#92]
**Describe the bug**
FlatKit water shader wave geometry has no vertex displacement, causing the surface to appear flat at all times, amplitude has no effect.

**To Reproduce**
1. Make new unity project using 3D URP template, using 2021.3.12f1
2. Import flat kit, import URP assets
3. Open pool demo

**Expected behavior**
Some of the water objects should have waves, but they do not.
Adjusting the amplitude parameter in the shader should have an effect, yet the surface remains flat.

**Unity details:**
 - Flat Kit version: 3.1.0 (november 16), just updated
 - Unity version: 2021.3.12f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 12.1.7
 - Development OS: Windows 10

**Comment by dustyroom-studio** [comment]
Thanks for reporting this, we're working on a fix.

**Comment by dustyroom-studio** [comment]
We've updated the asset with a fix, please re-download and re-import from the Asset Store.
