### ISSUE TITLE
Shadow edges becomes thicker

### ISSUE THREAD

**Issue by AntonTsirov** [Dustyroom/flat-kit-doc#95]
Hi there, I am trying out the shaders and noticed the following:

In the screenshot below you could see an example of the problem.
![image](https://user-images.githubusercontent.com/42478828/204142533-f9622e0d-a295-47c0-baac-6a498f1a831c.png)
![image](https://user-images.githubusercontent.com/42478828/204142564-ee691ffa-eb73-46e8-afe1-866a0a094bc1.png)

This ONLY happens when you get close to the shadows with the player.

These are the settings of the ground shader:
![image](https://user-images.githubusercontent.com/42478828/204142670-48f8476d-347a-4fdd-8a47-06edc07dbcc6.png)

These are the settings of the wall, that is casting the shadow:
![image](https://user-images.githubusercontent.com/42478828/204142803-01c89b87-ec61-44e6-883b-69492b35e552.png)

URP settings:
![image](https://user-images.githubusercontent.com/42478828/204143149-db1eec3b-71b1-466d-807b-0c4fb47e30f7.png)

**Unity details:**
 - Flat Kit version: 3.1.0
 - Unity version: 2020.3.24f1
 - Graphics Pipeline: URP
 - Development OS: Windows

**Comment by dustyroom-studio** [comment]
Hi Anton,

I see the arrows, but not sure what the problem is. Can you elaborate on the issue in text?

**Comment by AntonTsirov** [comment]
Hi, thank you for the fast response.

Sorry, I should have included a screenshot with how it looks without the "bug" (no idea what it is or the reason for it).

So, again the same blue wall and the shadow it cast:
![image](https://user-images.githubusercontent.com/42478828/204157421-41b4bb58-a3e0-4dd1-9ce2-8890e07784b8.png)
Now, the same blue wall shadow, the the player and camera are on the other side. You can see a difference in the shadow in the bottom left corner. It has some additional bumps added to it:
![image](https://user-images.githubusercontent.com/42478828/204157432-eafbb27a-bbc4-4cda-92c0-2b856f9491da.png)

**Comment by dustyroom-studio** [comment]
Thanks for clarifying! The jagged lines on the shadows could happen based on your shadow resolution and cascades settings, as well as the `Sharpness` value (in `Unity Built-in Shadows` section of the material). If that happens when using a standard Unity shader as well, please check [Shadow troubleshooting](https://docs.unity3d.com/Manual/ShadowPerformance.html).

**Comment by AntonTsirov** [comment]
Ahh, nice! Thank you. It was indeed caused by the cascade. I reduced it to 2 and now it doesn't happen. Cheers.
