### ISSUE TITLE
Assertion failed and inability to preview camera

### ISSUE THREAD

**Issue by chibi-goku** [Dustyroom/flat-kit-doc#98]
**Describe the bug**
I have a renderer with the Flat Kit Fog renderer feature enabled.
If I select the camera gameobject, the camera preview that appears on the scene editor only show the fog and the console shows the following assertion:

Assertion failed
UnityEngine.Rendering.RTHandle:op_Implicit (UnityEngine.Rendering.RTHandle)
FlatKit.BlitTexturePass:Execute (UnityEngine.Rendering.ScriptableRenderContext,UnityEngine.Rendering.Universal.RenderingData&) (at Assets/FlatKit/[Render Pipeline] URP/RenderFeatures/Common/BlitTexturePass.cs:69)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

**To Reproduce**
Create a renderer with the fog renderer feature, create a camera, click the camera on the hierarchy.

**Expected behavior**
I should be able to see the camera preview in the scene view.

**Screenshots**
Screenshot below.

**Unity details:**
 - Flat Kit version: 3.1.0
 - Unity version: 2022.2.0.f1
 - Graphics Pipeline: URP
 - URP version (if applicable): [e.g. 10.3.1]
 - Development OS: macOS Ventura

**Build platform:**
 - Platform: iOS
 - Test device: iPhone, but the problem is apparent on the editor.

**Additional context**
<img width="2029" alt="Screenshot 2022-12-14 at 22 09 55" src="https://user-images.githubusercontent.com/115844750/207725945-c825ad7d-789c-4fee-87f3-225955a296d3.png">

**Comment by dustyroom-studio** [comment]
Thanks for reporting this.

I can't reproduce this so far, (in the same Unity version):
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/74666746/207730512-853cb47e-5a32-4e34-80d5-00f4935343f1.png">

A few questions to help us debug:
- Does this happen in the Valley demo scene for you?
- Did you import Flat Kit into Unity 2022.2, or did you import it in a previous version and the upgraded?

**Comment by chibi-goku** [comment]
It was being used on a previous version and then imported into 2022.2. I'll reinstall Flatkit and get back to you.

**Comment by chibi-goku** [comment]
Reinstalling Flatkit fixed it. Thanks for the speedy reply.
