### ISSUE TITLE
Failing to load the URP Pipeline Asset

### ISSUE THREAD

**Issue by trojanfoe** [Dustyroom/flat-kit-doc#99]
**Describe the bug**
When pressing *Configure for URP* in the Readme tool, I am getting the error `Couldn't load the URP pipeline asset`.

**To Reproduce**
Follow the quick start video from YouTube.  I deselected all of `Water` and all of `Demo` as I do not require them.

**Expected behavior**
It configures the project for URP without issue.

**Unity details:**
Flat Kit version 3.2.0
Unity 2022.2.1f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 14.0.4
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: URP-HighFidelity
Graphics config: URP-HighFidelity

**Build platform:**
Windows

**Additional context**
The `path` is empty in `ReadmeEditor.cs:308`.  I would recommend changing line 309 to use `string.IsNullOrEmpty()` to catch this, instead of checking for `null` alone:

```
if (string.IsNullOrEmpty(path)) {
```

**Comment by trojanfoe** [comment]
Deleting the imported directories and re-importing everything still shows the same error. 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/312617/209938494-b2f98df8-1450-4e46-809d-c60bacbddeda.png">

**Comment by dustyroom-studio** [comment]
Hi,

Thank you for such a detailed report.

The _[Readme]_ tool's _'Configure Project for URP'_ button makes it quick for the Demo scenes to be set up correctly out of the box — using a prepared URP Pipeline Asset file and its Renderer + Renderer Features _per each scene_.

In a standard URP project, you have a URP Pipeline Asset file that lists all the Renderers (fka Forward Renderers) for the entire project. We used to have such a setup in Flat Kit as well up until one of the latest updates. But such a workflow is too cumbersome. Recently we added a per-scene URP Pipeline Asset loader script on camera components, which lets you have separate independent URP settings for each scene within a project. This makes it very easy and fast to duplicate scenes, do quick A/B comparison etc.

If you are not planning to use the Demo scenes, you can skip this installation step. You'll need to use your own URP Pipeline Asset file and its Renderer(s) in your custom scene then.

Thank you very much for bringing this to our attention! We'll make fixes to the [Readme] tool (like a note that you don't use Demos scenes) and update the doc to explain this workflow as soon as possible.

Please, let us know if you still have issues.

**Comment by trojanfoe** [comment]
Thank you very much for your quick and thorough response. I will respond more fully tomorrow when I have a chance to look at the things you suggest.

**Comment by trojanfoe** [comment]
Had a quick look now and everyone you have said makes perfect sense.  The new shaders are working lovely and thank you for your excellent support!  Have a great new year!

<img width="432" alt="image" src="https://user-images.githubusercontent.com/312617/209992090-bc7de671-e802-43ac-882d-eb97d0894a74.png">
